"""Slotless surface-PM motor torque-vs-angle plots (Epic #448 P3b).

Renders the capstone locked-rotor benchmark: the driven PM-vs-stator
interaction torque ``T(theta_r)`` vs the exact closed-form oracle. The
analytic ``T(theta_r) = -(2*pi*L/mu0)*C_M*G_S*cos(p*theta_r)`` is a solid
line; the FEM Arkkio (preferred) and Maxwell-line estimators are scatter
markers. A secondary thin axis shows the per-point Arkkio error relative
to the torque amplitude so the sub-2% agreement is visible at a glance.

Data source:

- ``benchmarks/motor/results.toml`` — auto-generated by
  ``cargo run -p geode-core --release --example motor_torque``. Records
  a ``[meta]`` block (pole pairs, drive, torque amplitude, sweep L2s)
  plus one ``[point_N]`` table per swept rotor angle
  (``theta_r, T_analytic, T_arkkio, T_line, rel_err_arkkio``).

Subtitle echoes the first caveat from ``meta.notes`` (typically the
Arkkio-vs-line estimator choice).

Single public entry point:

- :func:`plot_torque_vs_angle` — ``T(theta_r)`` overlay with FEM scatter,
  analytic line, and an Arkkio relative-error secondary axis.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np

from geode_viz.io import load_results
from geode_viz.plots._common import (
    iter_points as _iter_points,
    resolve_out as _resolve_out,
    subtitle_from_notes as _subtitle_from_notes,
)
from geode_viz.style import apply_style, footer


def _sweep_arrays(results: dict[str, Any]) -> dict[str, np.ndarray]:
    """Extract theta_r / T / rel-err arrays from a motor results TOML."""
    theta: list[float] = []
    t_analytic: list[float] = []
    t_arkkio: list[float] = []
    t_line: list[float] = []
    err_arkkio: list[float] = []
    for point in _iter_points(results):
        theta.append(float(point["theta_r"]))
        t_analytic.append(float(point["T_analytic"]))
        t_arkkio.append(float(point["T_arkkio"]))
        t_line.append(float(point["T_line"]))
        err_arkkio.append(float(point["rel_err_arkkio"]))
    return {
        "theta_r": np.asarray(theta, dtype=float),
        "T_analytic": np.asarray(t_analytic, dtype=float),
        "T_arkkio": np.asarray(t_arkkio, dtype=float),
        "T_line": np.asarray(t_line, dtype=float),
        "rel_err_arkkio": np.asarray(err_arkkio, dtype=float),
    }


def _draw_torque(
    ax_t: "plt.Axes",
    ax_e: "plt.Axes",
    results: dict[str, Any],
) -> None:
    """Draw the T-vs-theta + relative-error panels onto two axes.

    The axis-only core shared by the standalone
    :func:`plot_torque_vs_angle` and the tearsheet composer. ``ax_t`` is
    the (taller) torque panel; ``ax_e`` the (thinner) relative-error
    strip — they share the theta_r x-axis. No figure-level scaffolding
    (suptitle / footer / savefig) is touched.
    """
    arrays = _sweep_arrays(results)
    # Plot in electrical degrees for readability (p * theta_r * 180/pi).
    p = float(results.get("pole_pairs", 1))
    theta_elec_deg = np.degrees(arrays["theta_r"] * p)

    t_a = arrays["T_analytic"]
    t_ark = arrays["T_arkkio"]
    t_line = arrays["T_line"]
    err_ark = arrays["rel_err_arkkio"]

    # --- Torque panel: analytic line + FEM scatter ------------------------
    ax_t.plot(
        theta_elec_deg,
        t_a,
        color="#3b528b",
        linestyle="-",
        linewidth=1.6,
        label="T(θ_r) analytic (PM×stator)",
    )
    ax_t.scatter(
        theta_elec_deg,
        t_ark,
        marker="o",
        color="#21918c",
        s=42.0,
        edgecolor="black",
        linewidth=0.5,
        zorder=3,
        label="T Arkkio (FEM, preferred)",
    )
    ax_t.scatter(
        theta_elec_deg,
        t_line,
        marker="s",
        color="#7f7f7f",
        s=30.0,
        edgecolor="black",
        linewidth=0.4,
        zorder=3,
        alpha=0.8,
        label="T Maxwell line (FEM)",
    )
    ax_t.axhline(0.0, color="#bbbbbb", linewidth=0.7, zorder=0)
    ax_t.set_ylabel("Torque per length  T  (N·m/m)")
    ax_t.legend(loc="best", fontsize=8)

    # --- Error panel: |Arkkio rel err| in % on a log y-axis ---------------
    pct_floor = 1.0e-3  # 0.001 % floor so log-scale keeps every point.
    err_pct = np.maximum(np.abs(err_ark) * 100.0, pct_floor)
    ax_e.plot(
        theta_elec_deg,
        err_pct,
        marker="o",
        linestyle="-",
        color="#21918c",
        markersize=4.5,
        label="|Arkkio err| / |T|_max",
    )
    ax_e.set_yscale("log")
    ax_e.set_ylabel("|rel err| (%)")
    ax_e.set_xlabel("electrical angle  p·θ_r  (deg)")
    ax_e.legend(loc="best", fontsize=8)
    # Faint guides at the 5 % pass bar and the 2 % stretch target.
    ax_e.axhline(5.0, color="#d62728", linewidth=0.7, linestyle=":", alpha=0.6)
    ax_e.axhline(2.0, color="#ff7f0e", linewidth=0.7, linestyle=":", alpha=0.6)


def plot_torque_vs_angle(
    out: Path | None = None,
    *,
    ax: "plt.Axes | None" = None,
) -> Path | tuple["plt.Axes", "plt.Axes"]:
    """Plot the locked-rotor ``T(theta_r)`` FEM-vs-analytic overlay.

    Two-panel figure:

    - Upper (taller): the analytic interaction torque ``T(theta_r)``
      (solid line) with the FEM Arkkio and Maxwell-line estimators
      (scatter).
    - Lower (thin): the per-point Arkkio error relative to the torque
      amplitude (|err| in percent) on a log-scale y-axis, with faint 5 %
      pass-bar and 2 % stretch-target guides.

    Parameters
    ----------
    out
        Optional output PNG path. Defaults to
        ``artifacts/viz/motor/torque_vs_angle.png``. Ignored when ``ax``
        is supplied.
    ax
        Optional pre-existing axes whose grid slot is subdivided into the
        torque + relative-error rows (used by the tearsheet composer).
        When supplied the panels are drawn into a 2-row subgridspec carved
        from ``ax`` and the two new axes returned without creating a
        standalone figure or writing a PNG. When ``None`` the standalone
        two-panel figure is built.

    Returns
    -------
    Path or tuple of matplotlib.axes.Axes
        The resolved PNG path when ``ax is None``; otherwise the
        ``(ax_t, ax_e)`` panel axes drawn into.
    """
    results = load_results("motor", filename="results.toml")

    if ax is not None:
        fig = ax.get_figure()
        gridspec = ax.get_subplotspec().subgridspec(
            2, 1, height_ratios=[3.0, 1.2], hspace=0.08
        )
        ax.remove()
        ax_t = fig.add_subplot(gridspec[0])
        ax_e = fig.add_subplot(gridspec[1], sharex=ax_t)
        _draw_torque(ax_t, ax_e, results)
        return ax_t, ax_e

    apply_style("light")
    fig, (ax_t, ax_e) = plt.subplots(
        nrows=2,
        ncols=1,
        sharex=True,
        figsize=(7.5, 6.5),
        gridspec_kw={"height_ratios": [3.0, 1.2]},
    )
    _draw_torque(ax_t, ax_e, results)

    subtitle = _subtitle_from_notes(results)
    base_title = "Slotless-PM motor: locked-rotor T(θ_r)"
    if subtitle is None:
        fig.suptitle(base_title, fontsize=13)
    else:
        fig.suptitle(base_title + "\n" + subtitle, fontsize=11)

    footer(fig, results)

    out_path = _resolve_out("motor", out, "torque_vs_angle.png")
    fig.savefig(out_path)
    plt.close(fig)
    return out_path


__all__ = ["plot_torque_vs_angle"]
