"""Build report (`BOOK_REPORT.md`) for `anvil:project-book` (issue #596).

Renders the portfolio-style build report: a per-thread table (slug,
resolved version, lifecycle state, review score/total, audit state,
recommended next command) plus a "Build warnings" section listing every
quality warning surfaced during collection and staging. The report is a
build artifact — written at the project root on every apply-mode run,
gitignored alongside the chapters dir. It is source-of-truth for nothing;
it exists so the operator sees, at a glance, which chapters have and have
not converged before shipping a preview PDF.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from .collect import ThreadInfo
from .compile import CompileResult


def _version_cell(info: ThreadInfo) -> str:
    if info.resolved_name is None:
        return "(none)"
    slug = info.slug
    name = info.resolved_name
    if name.startswith(slug + "."):
        return name[len(slug):]  # e.g. ".5"
    return name


def _score_cell(info: ThreadInfo) -> str:
    if info.score is None:
        return "—"
    total = info.rubric_total if info.rubric_total is not None else "?"
    return f"{info.score}/{total}"


def _audit_cell(info: ThreadInfo) -> str:
    return info.audit_state if info.audit_state is not None else "—"


def _next_cell(info: ThreadInfo) -> str:
    return info.next_command if info.next_command is not None else "—"


def render_report(
    *,
    project_name: str,
    threads: List[ThreadInfo],
    ordering_source: str,
    excluded_slugs: Optional[List[str]] = None,
    master_doc: Optional[str] = None,
    out_pdf: Optional[str] = None,
    compile_result: Optional[CompileResult] = None,
    refusal_reason: Optional[str] = None,
    gitignore_note: Optional[str] = None,
) -> str:
    """Render the ``BOOK_REPORT.md`` markdown."""
    excluded_slugs = excluded_slugs or []
    lines: List[str] = []
    lines.append(f"# Book build report: {project_name}")
    lines.append("")
    lines.append(
        "<!-- Generated by anvil:project-book. Build artifact — not "
        "source-of-truth; safe to gitignore and regenerate. -->"
    )
    lines.append("")
    lines.append(f"**Chapters**: {len(threads)}")
    lines.append(f"**Ordering**: {ordering_source}")
    if master_doc is not None:
        lines.append(f"**Master document**: `{master_doc}`")
    else:
        lines.append(
            "**Master document**: (none — staging-only run; no compile)"
        )
    if out_pdf is not None:
        lines.append(f"**Output PDF**: `{out_pdf}`")

    if compile_result is not None:
        if compile_result.xelatex_missing:
            lines.append(
                "**Compile**: SKIPPED — xelatex not on PATH (chapters "
                "staged for manual compile)"
            )
        elif compile_result.attempted and compile_result.gate is not None:
            status = "PASS" if compile_result.gate.passed else "FAIL"
            lines.append(
                f"**Compile**: {status} "
                f"({compile_result.passes}-pass XeLaTeX)"
            )
    lines.append("")

    if refusal_reason is not None:
        lines.append("## Staging refused")
        lines.append("")
        lines.append(f"- {refusal_reason}")
        lines.append("")

    lines.append("## Chapters")
    lines.append("")
    lines.append(
        "| Thread | Version | State | Score | Audit | Next command |"
    )
    lines.append(
        "|--------|---------|-------|-------|-------|--------------|"
    )
    for info in threads:
        lines.append(
            f"| `{info.slug}` | {_version_cell(info)} | {info.state} | "
            f"{_score_cell(info)} | {_audit_cell(info)} | "
            f"{_next_cell(info)} |"
        )
    lines.append("")

    if excluded_slugs:
        lines.append("## Excluded")
        lines.append("")
        for slug in excluded_slugs:
            lines.append(
                f"- `{slug}`: listed in BRIEF.documents but omitted from "
                f"`build.order`."
            )
        lines.append("")

    # Build warnings — every warning from collection + staging.
    warnings: List[str] = []
    for info in threads:
        warnings.extend(info.warnings)
    if compile_result is not None and compile_result.xelatex_missing:
        warnings.append(
            "xelatex not on PATH — the book was not compiled. "
            + (compile_result.remediation or "")
        )
    elif (
        compile_result is not None
        and compile_result.attempted
        and compile_result.gate is not None
        and not compile_result.gate.passed
    ):
        for reason in compile_result.gate.reasons:
            warnings.append(f"compile: {reason}")

    lines.append("## Build warnings")
    lines.append("")
    if warnings:
        for w in warnings:
            lines.append(f"- {w}")
    else:
        lines.append("- None — every chapter resolved and converged.")
    lines.append("")

    placeholders = [t.slug for t in threads if t.needs_placeholder]
    if placeholders:
        lines.append(
            "> Placeholder chapters were generated for: "
            + ", ".join(f"`{s}`" for s in placeholders)
            + ". The book compiles, but these chapters are not yet written."
        )
        lines.append("")

    if gitignore_note is not None:
        lines.append(f"_Suggestion_: {gitignore_note}")
        lines.append("")

    return "\n".join(lines) + "\n"


def write_report(project_dir: Path, report_filename: str, content: str) -> Path:
    """Write ``content`` to ``<project_dir>/<report_filename>`` and return the path."""
    path = Path(project_dir) / report_filename
    path.write_text(content, encoding="utf-8")
    return path


__all__ = ["render_report", "write_report"]
