//! Layout → Gmsh `.geo` script (issue #704).
//!
//! Emits an OpenCASCADE script in the style of the hand-written
//! `reference/gmsh/{spiral_inductor,patch_antenna}.geo` fixtures:
//! dielectric slabs and conductor solids as `Box`es, PEC sheets and port
//! rectangles as `Rectangle`s, one `BooleanFragments` for conformal
//! interfaces, then **bounding-box** physical-group selection (robust to
//! OCC's post-boolean renumbering) with mechanically derived names, a
//! distance/threshold size field, and pinned output options (MSH 4.1
//! ASCII, linear elements, single-threaded meshing for determinism).

use std::fmt::Write as _;

use crate::mesh_cmd::layout::{BoundaryDef, OUTER_BOUNDARY, Rect, ResolvedLayout};

/// What a generated physical group is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GroupRole {
    /// Dielectric slab `i` (dimension 3).
    Dielectric(usize),
    /// Conductor layer `i` (dimension 2, PEC).
    Conductor(usize),
    /// Port `i` (dimension 2).
    Port(usize),
    /// The six outer walls (dimension 2, PEC).
    OuterBoundary,
}

/// One generated physical group.
#[derive(Debug, Clone)]
pub struct GroupDef {
    /// `3` (volume) or `2` (surface).
    pub dim: i32,
    /// Numeric physical tag.
    pub tag: i32,
    /// Physical-group name.
    pub name: String,
    /// What it is.
    pub role: GroupRole,
}

/// A generated script plus its physical-group table.
#[derive(Debug, Clone)]
pub struct GeoScript {
    /// `.geo` source.
    pub text: String,
    /// Groups, in tag order within each dimension.
    pub groups: Vec<GroupDef>,
}

/// First surface-group tag (volume groups count up from 1).
const FIRST_SURFACE_TAG: i32 = 101;

/// Shortest round-trip decimal form of `v` (never `NaN`/`inf`: the
/// layout is validated).
fn num(v: f64) -> String {
    let s = format!("{v:?}");
    s.strip_suffix(".0").map(str::to_owned).unwrap_or(s)
}

/// `Surface/Volume In BoundingBox{…}` of `r × [z0, z1]` grown by `eps`.
fn bbox_sel(kind: &str, r: &Rect, z0: f64, z1: f64, eps: f64) -> String {
    format!(
        "{kind} In BoundingBox{{{}, {}, {}, {}, {}, {}}}",
        num(r.x0 - eps),
        num(r.y0 - eps),
        num(z0 - eps),
        num(r.x1 + eps),
        num(r.y1 + eps),
        num(z1 + eps)
    )
}

/// Generate the script for a validated layout.
pub fn generate(r: &ResolvedLayout, generator: &str) -> GeoScript {
    let l = &r.layout;
    let d = r.domain;
    let (z_min, z_max) = (r.z_min, r.z_max);
    let extent = (d.x1 - d.x0).max(d.y1 - d.y0).max(z_max - z_min);
    // Selection tolerance: far below every feature, far above OCC's
    // bounding-box slack.
    let min_feature = r
        .conductor_rects
        .iter()
        .flatten()
        .chain(r.ports.iter().map(|p| &p.rect))
        .flat_map(|q| [q.x1 - q.x0, q.y1 - q.y0])
        .chain(
            l.conductors
                .iter()
                .map(|c| c.thickness)
                .filter(|t| *t > 0.0),
        )
        .chain(l.dielectrics.iter().map(|s| s.thickness))
        .fold(f64::INFINITY, f64::min);
    let eps = (1e-5 * extent).min(1e-3 * min_feature);

    let mut g = String::new();
    let w = &mut g;
    let _ = writeln!(w, "// Generated by {generator} from a layout (schema v1).");
    let _ = writeln!(
        w,
        "// Do not edit: regenerate with `geode mesh` (issue #704)."
    );
    let _ = writeln!(w, "//");
    let _ = writeln!(w, "// Physical groups:");
    let mut groups = Vec::new();
    for (i, s) in l.dielectrics.iter().enumerate() {
        groups.push(GroupDef {
            dim: 3,
            tag: i as i32 + 1,
            name: s.name.clone(),
            role: GroupRole::Dielectric(i),
        });
    }
    let mut tag = FIRST_SURFACE_TAG;
    let mut next = || {
        tag += 1;
        tag - 1
    };
    for (i, c) in l.conductors.iter().enumerate() {
        groups.push(GroupDef {
            dim: 2,
            tag: next(),
            name: c.name.clone(),
            role: GroupRole::Conductor(i),
        });
    }
    for (i, p) in r.ports.iter().enumerate() {
        groups.push(GroupDef {
            dim: 2,
            tag: next(),
            name: p.name.clone(),
            role: GroupRole::Port(i),
        });
    }
    groups.push(GroupDef {
        dim: 2,
        tag: next(),
        name: OUTER_BOUNDARY.into(),
        role: GroupRole::OuterBoundary,
    });
    let _ = writeln!(w, "//   | dim | tag | name | role |");
    for gd in &groups {
        let role = match gd.role {
            GroupRole::Dielectric(_) => "dielectric slab",
            GroupRole::Conductor(i) if l.conductors[i].thickness == 0.0 => "PEC sheet",
            GroupRole::Conductor(_) => "PEC shell",
            GroupRole::Port(_) => "lumped gap port",
            GroupRole::OuterBoundary => "outer walls (PEC)",
        };
        let _ = writeln!(w, "//   | {} | {} | {} | {role} |", gd.dim, gd.tag, gd.name);
    }
    let _ = writeln!(w);
    let _ = writeln!(w, "SetFactory(\"OpenCASCADE\");");
    let _ = writeln!(w);

    // --- Solids and sheets -------------------------------------------
    let (lx, ly) = (d.x1 - d.x0, d.y1 - d.y0);
    let mut vols = Vec::new();
    let mut surfs = Vec::new();
    let _ = writeln!(w, "// Dielectric slabs (full lateral domain).");
    for (i, s) in l.dielectrics.iter().enumerate() {
        let v = format!("v_d{i}");
        let _ = writeln!(
            w,
            "{v} = newv; Box({v}) = {{{}, {}, {}, {}, {}, {}}}; // {}",
            num(d.x0),
            num(d.y0),
            num(s.z_bottom),
            num(lx),
            num(ly),
            num(s.thickness),
            s.name
        );
        vols.push(v);
    }
    if let BoundaryDef::Upml { thickness: t, .. } = l.boundary {
        let _ = writeln!(
            w,
            "// UPML inner wall (conformal split of every slab at depth {}).",
            num(t)
        );
        let _ = writeln!(
            w,
            "v_upml = newv; Box(v_upml) = {{{}, {}, {}, {}, {}, {}}};",
            num(d.x0 + t),
            num(d.y0 + t),
            num(z_min + t),
            num(lx - 2.0 * t),
            num(ly - 2.0 * t),
            num(z_max - z_min - 2.0 * t)
        );
        vols.push("v_upml".into());
    }
    for (i, (c, rects)) in l.conductors.iter().zip(&r.conductor_rects).enumerate() {
        if c.thickness > 0.0 {
            let _ = writeln!(w, "// Conductor `{}`: PEC shell solids.", c.name);
            for (j, q) in rects.iter().enumerate() {
                let v = format!("v_c{i}_{j}");
                let _ = writeln!(
                    w,
                    "{v} = newv; Box({v}) = {{{}, {}, {}, {}, {}, {}}};",
                    num(q.x0),
                    num(q.y0),
                    num(c.z_bottom),
                    num(q.x1 - q.x0),
                    num(q.y1 - q.y0),
                    num(c.thickness)
                );
                vols.push(v);
            }
        } else {
            let _ = writeln!(w, "// Conductor `{}`: PEC sheets.", c.name);
            for (j, q) in rects.iter().enumerate() {
                let s = format!("s_c{i}_{j}");
                let _ = writeln!(
                    w,
                    "{s} = news; Rectangle({s}) = {{{}, {}, {}, {}, {}}};",
                    num(q.x0),
                    num(q.y0),
                    num(c.z_bottom),
                    num(q.x1 - q.x0),
                    num(q.y1 - q.y0)
                );
                surfs.push(s);
            }
        }
    }
    let _ = writeln!(w, "// Port rectangles.");
    for (i, p) in r.ports.iter().enumerate() {
        let s = format!("s_p{i}");
        let q = &p.rect;
        let _ = writeln!(
            w,
            "{s} = news; Rectangle({s}) = {{{}, {}, {}, {}, {}}}; // {}",
            num(q.x0),
            num(q.y0),
            num(p.z),
            num(q.x1 - q.x0),
            num(q.y1 - q.y0),
            p.name
        );
        surfs.push(s);
    }
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "// Conformal interfaces between every slab, solid, sheet and port."
    );
    let _ = writeln!(
        w,
        "BooleanFragments{{ Volume{{{}}}; Delete; }}{{ Surface{{{}}}; Delete; }}",
        vols.join(", "),
        surfs.join(", ")
    );
    let _ = writeln!(w);

    // --- Physical groups (bounding-box selection) --------------------
    let _ = writeln!(
        w,
        "// Physical groups: bounding-box selection (robust to OCC renumbering)."
    );
    for gd in groups.iter().filter(|g| g.dim == 3) {
        let GroupRole::Dielectric(i) = gd.role else {
            continue;
        };
        let s = &l.dielectrics[i];
        let _ = writeln!(
            w,
            "g_{}() = {};",
            gd.tag,
            bbox_sel("Volume", &d, s.z_bottom, s.z_bottom + s.thickness, eps)
        );
        let _ = writeln!(
            w,
            "Physical Volume(\"{}\", {}) = {{g_{}()}};",
            gd.name, gd.tag, gd.tag
        );
    }
    // Ports first: conductor selections exclude already-assigned faces
    // so no triangle lands in two groups.
    let _ = writeln!(w, "assigned() = {{}};");
    let ports_then_conductors = groups
        .iter()
        .filter(|g| matches!(g.role, GroupRole::Port(_)))
        .chain(
            groups
                .iter()
                .filter(|g| matches!(g.role, GroupRole::Conductor(_))),
        );
    for gd in ports_then_conductors {
        let body = match gd.role {
            GroupRole::Port(i) => {
                let p = &r.ports[i];
                vec![bbox_sel("Surface", &p.rect, p.z, p.z, eps)]
            }
            GroupRole::Conductor(i) => {
                let c = &l.conductors[i];
                r.conductor_rects[i]
                    .iter()
                    .map(|q| bbox_sel("Surface", q, c.z_bottom, c.z_top(), eps))
                    .collect()
            }
            _ => continue,
        };
        let t = gd.tag;
        let _ = writeln!(w, "g_{t}() = {{}};");
        for sel in body {
            let _ = writeln!(w, "g_{t}() += {sel};");
        }
        let _ = writeln!(w, "g_{t}() = Unique(g_{t}());");
        let _ = writeln!(w, "g_{t}() -= {{assigned()}};");
        let _ = writeln!(w, "assigned() += {{g_{t}()}};");
        let _ = writeln!(w, "Physical Surface(\"{}\", {t}) = {{g_{t}()}};", gd.name);
    }
    let outer = groups.last().expect("outer boundary");
    let t = outer.tag;
    let walls = [
        (Rect { ..d }, z_min, z_min),
        (Rect { ..d }, z_max, z_max),
        (Rect { x1: d.x0, ..d }, z_min, z_max),
        (Rect { x0: d.x1, ..d }, z_min, z_max),
        (Rect { y1: d.y0, ..d }, z_min, z_max),
        (Rect { y0: d.y1, ..d }, z_min, z_max),
    ];
    let _ = writeln!(w, "g_{t}() = {{}};");
    for (q, z0, z1) in walls {
        let _ = writeln!(w, "g_{t}() += {};", bbox_sel("Surface", &q, z0, z1, eps));
    }
    let _ = writeln!(w, "g_{t}() = Unique(g_{t}());");
    let _ = writeln!(
        w,
        "Physical Surface(\"{OUTER_BOUNDARY}\", {t}) = {{g_{t}()}};"
    );
    let _ = writeln!(w);

    // --- Size field ---------------------------------------------------
    let size_max = l.mesh.size_max;
    let far = r.far_distance();
    let mut field = 0;
    let mut thresholds = Vec::new();
    let _ = writeln!(
        w,
        "// Size field: refine near conductors and ports, grow to size_max."
    );
    for gd in &groups {
        let (size, near, extent) = match gd.role {
            GroupRole::Conductor(i) => {
                let size = r.conductor_size(i);
                let ext = r.conductor_rects[i]
                    .iter()
                    .map(|q| (q.x1 - q.x0).max(q.y1 - q.y0))
                    .fold(l.conductors[i].thickness, f64::max);
                (size, l.mesh.near_distance.unwrap_or(size), ext)
            }
            GroupRole::Port(i) => {
                let p = &r.ports[i];
                (r.port_size(), p.length, p.length.max(p.width))
            }
            _ => continue,
        };
        let sampling = ((2.0 * extent / size).ceil() as i64).clamp(20, 400);
        field += 1;
        let dist = field;
        let _ = writeln!(w, "Field[{dist}] = Distance;");
        let _ = writeln!(w, "Field[{dist}].SurfacesList = {{g_{}()}};", gd.tag);
        let _ = writeln!(w, "Field[{dist}].Sampling = {sampling};");
        field += 1;
        let _ = writeln!(w, "Field[{field}] = Threshold;");
        let _ = writeln!(w, "Field[{field}].InField = {dist};");
        let _ = writeln!(w, "Field[{field}].SizeMin = {};", num(size.min(size_max)));
        let _ = writeln!(w, "Field[{field}].SizeMax = {};", num(size_max));
        let _ = writeln!(w, "Field[{field}].DistMin = {};", num(near));
        let _ = writeln!(w, "Field[{field}].DistMax = {};", num(far.max(near)));
        thresholds.push(field.to_string());
    }
    field += 1;
    let _ = writeln!(w, "Field[{field}] = Min;");
    let _ = writeln!(
        w,
        "Field[{field}].FieldsList = {{{}}};",
        thresholds.join(", ")
    );
    let _ = writeln!(w, "Background Field = {field};");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "// Pinned options: sizes from the field only, linear elements,\n\
         // MSH 4.1 ASCII (what geode_core::mesh::read_tagged_tet_mesh reads),\n\
         // single-threaded for a reproducible mesh."
    );
    for opt in [
        "Mesh.MeshSizeExtendFromBoundary = 0;".to_string(),
        "Mesh.MeshSizeFromPoints = 0;".into(),
        "Mesh.MeshSizeFromCurvature = 0;".into(),
        format!("Mesh.MeshSizeMax = {};", num(size_max)),
        "Mesh.Algorithm = 6;".into(),
        "Mesh.Algorithm3D = 1;".into(),
        "Mesh.Optimize = 1;".into(),
        "Mesh.OptimizeNetgen = 0;".into(),
        "Mesh.ElementOrder = 1;".into(),
        "Mesh.SaveAll = 0;".into(),
        "Mesh.MshFileVersion = 4.1;".into(),
        "Mesh.Binary = 0;".into(),
        "General.NumThreads = 1;".into(),
    ] {
        let _ = writeln!(w, "{opt}");
    }
    GeoScript { text: g, groups }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mesh_cmd::layout::Layout;

    #[test]
    fn numbers_round_trip_compactly() {
        assert_eq!(num(1.0), "1");
        assert_eq!(num(-2.5), "-2.5");
        assert_eq!(num(1e-6), "1e-6");
        assert_eq!(num(0.1 + 0.2), "0.30000000000000004");
    }

    #[test]
    fn script_names_every_group_and_pins_msh41() {
        let l: Layout = serde_json::from_value(serde_json::json!({
            "schema_version": 1,
            "length_unit_m": 1e-6,
            "dielectrics": [
                {"name": "substrate", "z_bottom": -10, "thickness": 10, "eps_r": [11.9, 0]},
                {"name": "air", "z_bottom": 0, "thickness": 20}
            ],
            "conductors": [
                {"name": "m1", "z_bottom": 1, "polygons": [
                    {"name": "a", "outer": [[0, 0], [10, 0], [10, 4], [0, 4]]},
                    {"name": "b", "outer": [[0, 6], [10, 6], [10, 10], [0, 10]]}]},
                {"name": "via", "z_bottom": 1, "thickness": 3, "polygons": [
                    {"outer": [[0, 0], [2, 0], [2, 2], [0, 2]]}]}
            ],
            "ports": [{"name": "p1", "layer": "m1", "between": ["a", "b"]}],
            "margin": 5,
            "boundary": {"kind": "upml", "thickness": 2},
            "mesh": {"size_max": 5, "size_conductor": 1}
        }))
        .unwrap();
        let s = generate(&l.resolve().unwrap(), "test");
        let names: Vec<_> = s
            .groups
            .iter()
            .map(|g| (g.dim, g.tag, g.name.as_str()))
            .collect();
        assert_eq!(
            names,
            vec![
                (3, 1, "substrate"),
                (3, 2, "air"),
                (2, 101, "m1"),
                (2, 102, "via"),
                (2, 103, "p1"),
                (2, 104, "outer_boundary"),
            ]
        );
        for needle in [
            "Physical Volume(\"substrate\", 1)",
            "Physical Surface(\"p1\", 103)",
            "Physical Surface(\"outer_boundary\", 104)",
            "Mesh.MshFileVersion = 4.1;",
            "Mesh.Binary = 0;",
            "Mesh.ElementOrder = 1;",
            "v_upml = newv;",
            "Rectangle(s_c0_0) = {0, 0, 1, 10, 4};",
            "Box(v_c1_0) = {0, 0, 1, 2, 2, 3};",
        ] {
            assert!(s.text.contains(needle), "missing `{needle}` in\n{}", s.text);
        }
    }
}
