//! Root-for-root cross-check of the analytic Mie resonance catalogue
//! against the NumPy/SciPy reference (Issue #170, Epic #88 Phase J.1).
//!
//! Loads `reference/fixtures/mie_roots/baseline.json` (generated by
//! `reference/numpy/gen_mie_roots_baseline.py` from
//! `reference/numpy/mie_roots.py`) and joins the Burn-side
//! `geode_core::mie::{resonance_roots, merged_roots, mie_roots_catalog}`
//! output against it on the exact integer key `(pol, l, n)`.
//!
//! # Why this is the purest cross-check in Epic #88
//!
//! No mesh, no eigensolve — just special functions (spherical Bessel
//! `j_l`/`y_l` ladders) and root finding. The Rust side hand-rolls the
//! Bessel recurrences (upward for `l ≤ x + 1`, Miller's downward above)
//! and bisects to ~1e-12 relative; the SciPy side uses
//! `scipy.special.spherical_jn`/`spherical_yn` and `brentq`. Agreement
//! at ≤ 1e-10 relative therefore pins the *mathematics* (characteristic
//! functions, bracketing window, dedup) rather than any shared
//! implementation detail.
//!
//! # What is checked
//!
//! 1. Geometry constants: the fixture's `r_sphere` / `r_buffer` equal
//!    the Burn `mesh::{R_SPHERE, R_BUFFER}` constants bit-exactly (the
//!    catalogue is meaningless if the geometries drift apart).
//! 2. Root-*count* agreement per `(l, polarisation)` window — no missed
//!    or spurious roots (bracketing / pole-rejection parity).
//! 3. Root-for-root `(pol, l, n) → k` agreement at ≤ 1e-10 relative for
//!    `mie_roots_catalog(1.5, 4, 5)` (the exact extent
//!    `examples/mie_sphere.rs` consumes: `L_MAX = 4`, `N_MAX = 5`).
//! 4. `merged_roots` over `l = 1..=4` reproduces the same root set as
//!    `mie_roots_catalog` and matches the fixture too (the two public
//!    entry points must stay in lockstep).

use std::collections::BTreeMap;
use std::path::PathBuf;

use geode_core::{
    merged_roots, mie_roots_catalog, resonance_roots, MiePolarisation, MieRoot, R_BUFFER, R_SPHERE,
};
use geode_validation::{Fixture, FixtureFormat};

// ---------------------------------------------------------------------------
// Catalogue parameters — mirror examples/mie_sphere.rs and the fixture.
// ---------------------------------------------------------------------------

const N_INSIDE: f64 = 1.5;
const L_MAX: usize = 4;
const N_MAX: usize = 5;

/// Cross-check contract from issue #170: ≤ 1e-10 relative. The Rust
/// bisection terminates at ~1e-12 relative half-width and brentq at
/// machine precision, so the headroom is ~100×; anything beyond this
/// is a characteristic-function or bracketing disagreement, not
/// root-finder noise.
const REL_TOL: f64 = 1e-10;

// ---------------------------------------------------------------------------
// Fixture path resolution (same pattern as derham_numpy_reference.rs).
// ---------------------------------------------------------------------------

fn repo_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    for ancestor in manifest.ancestors() {
        if ancestor.join("reference").is_dir() {
            return ancestor.to_path_buf();
        }
    }
    panic!(
        "could not find a `reference/` directory walking up from {}",
        manifest.display()
    );
}

fn fixture_path() -> PathBuf {
    repo_root().join("reference/fixtures/mie_roots/baseline.json")
}

fn load_fixture() -> Fixture {
    Fixture::load_from(&fixture_path(), FixtureFormat::Json)
        .expect("mie_roots/baseline.json should load")
}

// ---------------------------------------------------------------------------
// Fixture field accessors.
// ---------------------------------------------------------------------------

fn fixture_scalar_f64(fixture: &Fixture, name: &str) -> f64 {
    let f = fixture
        .output_f64(name)
        .unwrap_or_else(|e| panic!("fixture missing scalar output `{name}`: {e}"));
    assert_eq!(
        f.data.len(),
        1,
        "fixture scalar `{name}` should be length 1, got {}",
        f.data.len()
    );
    f.data[0]
}

fn fixture_scalar_usize(fixture: &Fixture, name: &str) -> usize {
    fixture_scalar_f64(fixture, name).round() as usize
}

fn fixture_array_f64(fixture: &Fixture, name: &str) -> Vec<f64> {
    fixture
        .output_f64(name)
        .unwrap_or_else(|e| panic!("fixture missing array output `{name}`: {e}"))
        .data
        .clone()
}

fn fixture_array_usize(fixture: &Fixture, name: &str) -> Vec<usize> {
    fixture_array_f64(fixture, name)
        .iter()
        .map(|v| v.round() as usize)
        .collect()
}

/// Canonical join key: `(pol_index, l, n)` with `pol_index` 0 = TE,
/// 1 = TM — matching the fixture's `root_pol` encoding.
type RootKey = (u8, usize, usize);

fn pol_index(pol: MiePolarisation) -> u8 {
    match pol {
        MiePolarisation::TE => 0,
        MiePolarisation::TM => 1,
    }
}

fn pol_name(idx: u8) -> &'static str {
    match idx {
        0 => "TE",
        1 => "TM",
        _ => "??",
    }
}

/// Load the fixture's catalogue as a `(pol, l, n) → k` map, asserting
/// the parallel-array invariants (equal lengths, multiplicity = 2l+1,
/// no duplicate keys).
fn fixture_root_map(fixture: &Fixture) -> BTreeMap<RootKey, f64> {
    let n_roots = fixture_scalar_usize(fixture, "n_roots");
    let pols = fixture_array_usize(fixture, "root_pol");
    let ls = fixture_array_usize(fixture, "root_l");
    let ns = fixture_array_usize(fixture, "root_n");
    let mults = fixture_array_usize(fixture, "root_multiplicity");
    let ks = fixture_array_f64(fixture, "root_k");

    for (name, len) in [
        ("root_pol", pols.len()),
        ("root_l", ls.len()),
        ("root_n", ns.len()),
        ("root_multiplicity", mults.len()),
        ("root_k", ks.len()),
    ] {
        assert_eq!(len, n_roots, "`{name}` length {len} != n_roots {n_roots}");
    }

    let mut map = BTreeMap::new();
    for i in 0..n_roots {
        let key: RootKey = (pols[i] as u8, ls[i], ns[i]);
        assert!(pols[i] <= 1, "root_pol[{i}] = {} not in {{0, 1}}", pols[i]);
        assert_eq!(
            mults[i],
            2 * ls[i] + 1,
            "fixture multiplicity for {key:?} should be 2l+1"
        );
        assert!(
            ks[i].is_finite() && ks[i] > 0.0,
            "fixture k for {key:?} is {}, not a positive finite root",
            ks[i]
        );
        let prev = map.insert(key, ks[i]);
        assert!(prev.is_none(), "duplicate fixture key {key:?}");
    }
    map
}

/// Project a Burn-side root list into the same `(pol, l, n) → k` map.
fn burn_root_map(roots: &[MieRoot]) -> BTreeMap<RootKey, f64> {
    let mut map = BTreeMap::new();
    for r in roots {
        assert_eq!(
            r.multiplicity,
            2 * r.l + 1,
            "Burn multiplicity drift: {r:?}"
        );
        let key: RootKey = (pol_index(r.pol), r.l, r.n);
        let prev = map.insert(key, r.k);
        assert!(prev.is_none(), "duplicate Burn key {key:?}");
    }
    map
}

/// Join two `(pol, l, n) → k` maps: identical key sets (root-count /
/// labelling agreement) and per-root relative error ≤ `REL_TOL`.
fn assert_root_maps_agree(
    burn: &BTreeMap<RootKey, f64>,
    numpy: &BTreeMap<RootKey, f64>,
    context: &str,
) {
    // Key-set agreement first — a missed/spurious root is the
    // root-window-edge friction class issue #170 calls out, and it
    // should fail with the offending (pol, l, n), not a length number.
    for key in burn.keys() {
        assert!(
            numpy.contains_key(key),
            "{context}: Burn has root {}({}, n={}) that the NumPy \
             catalogue lacks (spurious bracket on the Burn side, or a \
             rejected/merged bracket on the SciPy side?)",
            pol_name(key.0),
            key.1,
            key.2
        );
    }
    for key in numpy.keys() {
        assert!(
            burn.contains_key(key),
            "{context}: NumPy has root {}({}, n={}) that the Burn \
             catalogue lacks (root-window edge effect?)",
            pol_name(key.0),
            key.1,
            key.2
        );
    }

    let mut worst_rel: f64 = 0.0;
    let mut worst_key: RootKey = (0, 0, 0);
    for (key, &k_burn) in burn {
        let k_numpy = numpy[key];
        let rel = (k_burn - k_numpy).abs() / k_numpy.abs();
        if rel > worst_rel {
            worst_rel = rel;
            worst_key = *key;
        }
        assert!(
            rel <= REL_TOL,
            "{context}: root {}(l={}, n={}) disagrees: Burn k = {k_burn:.15}, \
             NumPy k = {k_numpy:.15}, relative error {rel:.3e} > {REL_TOL:.0e}",
            pol_name(key.0),
            key.1,
            key.2
        );
    }
    println!(
        "{context}: {} roots agree; worst relative error {:.3e} at \
         {}(l={}, n={})",
        burn.len(),
        worst_rel,
        pol_name(worst_key.0),
        worst_key.1,
        worst_key.2
    );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn fixture_loads_with_canonical_schema() {
    let fixture = load_fixture();
    assert_eq!(fixture.fixture_id, "mie_roots/n15_pec_cavity_l4_n5");
    assert_eq!(fixture.schema_version, "1");

    for expected in [
        "l_max",
        "n_max",
        "n_roots",
        "n_inside",
        "r_sphere",
        "r_buffer",
        "root_pol",
        "root_l",
        "root_n",
        "root_multiplicity",
        "root_k",
        "root_count_te",
        "root_count_tm",
    ] {
        assert!(
            fixture.outputs.contains_key(expected),
            "fixture missing required output `{expected}`"
        );
    }

    assert_eq!(fixture_scalar_usize(&fixture, "l_max"), L_MAX);
    assert_eq!(fixture_scalar_usize(&fixture, "n_max"), N_MAX);
}

#[test]
fn geometry_constants_match_burn_bit_exact() {
    // The catalogue cross-check is meaningless if the two sides solve
    // different geometries — pin n / R_s / R_b bit-exactly (all three
    // are exactly representable: 1.5, 1.0, 2.0).
    let fixture = load_fixture();
    assert_eq!(fixture_scalar_f64(&fixture, "n_inside"), N_INSIDE);
    assert_eq!(fixture_scalar_f64(&fixture, "r_sphere"), R_SPHERE);
    assert_eq!(fixture_scalar_f64(&fixture, "r_buffer"), R_BUFFER);
}

#[test]
fn root_counts_agree_per_l_and_polarisation() {
    // Friction target #3 from issue #170: a root sitting on a
    // bracketing boundary appearing in one catalogue but not the
    // other. Count agreement per (l, polarisation) window is the
    // structural guard.
    let fixture = load_fixture();
    let count_te = fixture_array_usize(&fixture, "root_count_te");
    let count_tm = fixture_array_usize(&fixture, "root_count_tm");
    assert_eq!(
        count_te.len(),
        L_MAX,
        "root_count_te should cover l = 1..=L_MAX"
    );
    assert_eq!(
        count_tm.len(),
        L_MAX,
        "root_count_tm should cover l = 1..=L_MAX"
    );

    for l in 1..=L_MAX {
        for (pol, counts) in [
            (MiePolarisation::TE, &count_te),
            (MiePolarisation::TM, &count_tm),
        ] {
            let burn = resonance_roots(pol, N_INSIDE, l, R_SPHERE, R_BUFFER, N_MAX);
            assert_eq!(
                burn.len(),
                counts[l - 1],
                "root count mismatch for {pol:?} l = {l}: Burn found {}, \
                 NumPy catalogued {}",
                burn.len(),
                counts[l - 1]
            );
            // Radial-order labels must be the contiguous run 1..=count
            // in ascending-k order (both sides label by window order).
            for (idx, r) in burn.iter().enumerate() {
                assert_eq!(r.n, idx + 1, "{pol:?} l = {l}: non-contiguous radial order");
                assert_eq!(r.l, l);
                assert_eq!(r.pol, pol);
            }
        }
    }
}

#[test]
fn catalog_roots_match_numpy_root_for_root() {
    let fixture = load_fixture();
    let numpy = fixture_root_map(&fixture);

    let catalog = mie_roots_catalog(N_INSIDE, L_MAX, N_MAX);
    // Catalogue contract: globally sorted by ascending k.
    for w in catalog.windows(2) {
        assert!(w[0].k <= w[1].k, "mie_roots_catalog must be sorted by k");
    }
    let burn = burn_root_map(&catalog);

    assert_eq!(
        burn.len(),
        fixture_scalar_usize(&fixture, "n_roots"),
        "total root count: Burn vs fixture n_roots"
    );
    assert_root_maps_agree(&burn, &numpy, "mie_roots_catalog(1.5, 4, 5)");
}

#[test]
fn merged_roots_agree_with_catalog_and_numpy() {
    // The two public entry points must produce the same root set for
    // the same extent — and both must match the fixture.
    let fixture = load_fixture();
    let numpy = fixture_root_map(&fixture);

    let l_set: Vec<usize> = (1..=L_MAX).collect();
    let merged = merged_roots(N_INSIDE, &l_set, R_SPHERE, R_BUFFER, N_MAX);
    let merged_map = burn_root_map(&merged);

    let catalog_map = burn_root_map(&mie_roots_catalog(N_INSIDE, L_MAX, N_MAX));
    assert_eq!(
        merged_map, catalog_map,
        "merged_roots and mie_roots_catalog drifted apart for the same extent"
    );

    assert_root_maps_agree(
        &merged_map,
        &numpy,
        "merged_roots(1.5, [1..4], 1.0, 2.0, 5)",
    );
}
