//! Pointwise cross-check of the analytic Mie scattering efficiencies
//! against the NumPy/BHMIE reference (issue #195, Epic #193 Phase 1).
//!
//! Loads `reference/fixtures/mie_efficiencies/baseline.json`
//! (generated by `reference/numpy/gen_mie_efficiencies_baseline.py`
//! from `reference/numpy/mie_efficiencies.py`) and joins the Burn-side
//! `geode_core::mie_scattering::mie_efficiencies` output against it on
//! both the 5-point FEM-benchmark grid and the dense 60-point curve.
//!
//! # Why this pins the mathematics, not an implementation
//!
//! The two sides share only the Mie series itself:
//!
//! - **Rust** evaluates the Bohren & Huffman coefficient formulas
//!   directly — Riccati `ψ_l(mx)`/`ψ_l'(mx)` at the dielectric
//!   argument through the hand-rolled, Miller-stabilized spherical
//!   Bessel ladders of `geode_core::mie`.
//! - **NumPy** uses the BHMIE logarithmic-derivative algorithm: the
//!   interior solution enters only via the downward `D_n(mx)`
//!   recurrence, and `ψ`/`χ` come from SciPy's
//!   `spherical_jn`/`spherical_yn`.
//!
//! Agreement at ≤ 1e-10 absolute (`Q` is O(1) over the range)
//! therefore validates the series, the truncation (shared Wiscombe
//! criterion), and both Bessel stacks at once. No mesh, no solve —
//! the same "purest cross-check" tier as `mie_roots_numpy_reference`.

use std::collections::BTreeMap;
use std::path::PathBuf;

use geode_core::{mie_efficiencies, R_SPHERE};
use geode_validation::{Fixture, FixtureFormat};

const N_INSIDE: f64 = 1.5;

fn fixture_path() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    for ancestor in manifest.ancestors() {
        if ancestor.join("reference").is_dir() {
            return ancestor
                .join("reference")
                .join("fixtures")
                .join("mie_efficiencies")
                .join("baseline.json");
        }
    }
    panic!(
        "could not find a `reference/` directory walking up from {}",
        manifest.display()
    );
}

fn input_vec(fixture: &Fixture, name: &str) -> Vec<f64> {
    fixture.inputs[name]
        .data
        .as_array()
        .unwrap_or_else(|| panic!("input `{name}` should be an array"))
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect()
}

#[test]
fn fixture_loads_with_expected_schema() {
    let fixture = Fixture::load_from(&fixture_path(), FixtureFormat::Json)
        .expect("mie_efficiencies baseline.json should load");
    assert_eq!(fixture.schema_version, "1");
    assert_eq!(fixture.fixture_id, "mie_efficiencies/n15_qext_qsca");
    for key in ["n_inside", "r_sphere", "ka_benchmark", "ka_curve"] {
        assert!(
            fixture.inputs.contains_key(key),
            "missing input field '{key}'"
        );
    }
    for key in [
        "q_ext_benchmark",
        "q_sca_benchmark",
        "q_ext_curve",
        "q_sca_curve",
    ] {
        assert!(
            fixture.outputs.contains_key(key),
            "missing output field '{key}'"
        );
        assert_eq!(fixture.outputs[key].dtype, "f64");
    }

    // Geometry / material constants must match the Burn side exactly.
    let n = input_vec(&fixture, "n_inside");
    assert_eq!(n, vec![N_INSIDE]);
    let r = input_vec(&fixture, "r_sphere");
    assert_eq!(r, vec![R_SPHERE]);
}

#[test]
fn efficiencies_agree_with_numpy_on_both_grids() {
    let fixture = Fixture::load_from(&fixture_path(), FixtureFormat::Json)
        .expect("mie_efficiencies baseline.json should load");

    let mut actual: BTreeMap<String, Vec<f64>> = BTreeMap::new();
    for (ka_field, ext_field, sca_field) in [
        ("ka_benchmark", "q_ext_benchmark", "q_sca_benchmark"),
        ("ka_curve", "q_ext_curve", "q_sca_curve"),
    ] {
        let ka = input_vec(&fixture, ka_field);
        let effs: Vec<_> = ka.iter().map(|&x| mie_efficiencies(N_INSIDE, x)).collect();
        actual.insert(
            ext_field.to_string(),
            effs.iter().map(|e| e.q_ext).collect(),
        );
        actual.insert(
            sca_field.to_string(),
            effs.iter().map(|e| e.q_sca).collect(),
        );
    }

    let report = fixture.compare_against(&actual);
    if !report.passed {
        for f in &report.fields {
            eprintln!(
                "  field={} passed={} tol={:.0e} max_abs={:?}",
                f.field, f.passed, f.tolerance_abs, f.max_abs_error
            );
        }
        panic!("mie_efficiencies disagreed with the NumPy BHMIE baseline");
    }

    // Report the observed floor (expected ~1e-12: two independent
    // Bessel stacks + two independent algorithms at f64).
    let worst = report
        .fields
        .iter()
        .filter_map(|f| f.max_abs_error)
        .fold(0.0_f64, f64::max);
    eprintln!(
        "mie_efficiencies Burn vs NumPy/BHMIE: max |ΔQ| = {worst:.3e} over \
         {} fields (tolerance 1e-10)",
        report.fields.len()
    );
}

/// The FEM driven benchmark consumes the 5-point grid; pin those `ka`
/// values against the example's sweep so the fixture and the
/// benchmark cannot drift apart silently.
#[test]
fn benchmark_grid_matches_driven_benchmark_sweep() {
    let fixture = Fixture::load_from(&fixture_path(), FixtureFormat::Json)
        .expect("mie_efficiencies baseline.json should load");
    let ka = input_vec(&fixture, "ka_benchmark");
    // Mirror of examples/mie_driven_scattering.rs KA_VALUES and
    // tests/mie_driven_scattering.rs KA_BANDS.
    assert_eq!(ka, vec![1.0, 1.5, 1.9, 2.4, 3.0]);
}
