//! Cross-IR anisotropic-UPML Mie comparator against the Julia
//! **small-mesh** baseline (issue #172, Epic #88 Phase J.3 — Julia
//! sibling of `sphere_mie_numpy_reference.rs`, following the
//! `sphere_pml_julia_small_reference.rs` pattern from #160 / PR #167).
//!
//! Loads `reference/fixtures/sphere_mie_small/julia_baseline.json`
//! (generated by `reference/julia/gen_sphere_mie_small_baseline.jl`
//! from `reference/julia/sphere_mie_small.jl` — dense
//! `LinearAlgebra.eigen` on the 214-DOF interior tensor-ε pencil;
//! Arpack shift-invert explicitly avoided per the #160 lossy-cluster
//! saturation finding) and asserts:
//!
//! 1. **Schema conformance**: the J.2 sphere_mie field set with `c128`
//!    on `epsilon_tensor_diag` / `eigenvalues_lowest_complex` /
//!    `physical_eigenvalues_complex`.
//! 2. **Constitutive**: the Julia per-tet diagonal UPML tensor matches
//!    Burn's `build_anisotropic_pml_tensor_diag` at `1e-14` absolute
//!    (bit-exact f64 host math on both sides).
//! 3. **Spectrum (Burn vs Julia)**: Burn `FaerComplexEigensolver` (QZ)
//!    vs Julia LAPACK ZGGEV on the identical complex-symmetric
//!    tensor-ε pencil via the c128 comparator, with the strict
//!    cross-IR window = the first `strict_mode_window_len = 3` physical
//!    modes (the closed TM_1,1 triplet, #160 cluster-closure
//!    convention) and the small-mesh `Im(λ) < 0` sign assertion
//!    (PR #179 schema doc: the anisotropic pencil's physical Im sign is
//!    mesh-dependent).
//! 4. **Julia vs NumPy direct**: `physical_eigenvalues_complex` agrees
//!    with the J.2 NumPy small baseline at 5e-3 absolute on all 5 modes
//!    (measured ~1e-13 — LAPACK-vs-LAPACK on the identical pencil), and
//!    the σ₀ = 0 PEC anchors agree at 5e-5.
//! 5. **J.1 analytic anchor + Q tripwire**: the re-exported
//!    `analytic_tm11_k` matches `geode_core::analytic::mie::merged_roots` at 1e-9, the
//!    lowest mode sits inside the documented 8 % coarse-mesh band, and
//!    Q stays above the `Q_LOWER_BAND_TM11 = 1.5` tripwire.
//!
//! # Running
//!
//! ```sh
//! cargo test -p geode-validation --test sphere_mie_julia_small_reference
//! ```

use std::collections::BTreeMap;
use std::path::PathBuf;

use burn::tensor::backend::BackendTypes;
use num_complex::Complex64;

use geode_core::analytic::mie::{MiePolarisation, merged_roots};
use geode_core::assembly::nedelec::{
    assemble_global_nedelec_with_anisotropic_epsilon, build_anisotropic_pml_tensor_diag,
    burn_complex_mass_to_faer, sphere_n_interior_nodes, sphere_pec_interior_edges, tet_centroids,
};
use geode_core::assembly::p1::upload_mesh;
use geode_core::testing::TestBackend;
use geode_core::eigen::complex::{ComplexEigenSolver, FaerComplexEigensolver};
use geode_core::eigen::dense::{apply_dirichlet_bc, burn_matrix_to_faer};
use geode_core::mesh::{R_BUFFER, R_SPHERE, SphereFixture, read_sphere_fixture_from_bytes};
use geode_validation::diff::FieldStatus;
use geode_validation::{Fixture, FixtureFormat};

type B = TestBackend;

/// Q-factor lower band for the TM_1,1 triplet — mirror of
/// `Q_LOWER_BAND_TM11` in `crates/geode-core/tests/mie_sphere.rs`.
const Q_LOWER_BAND_TM11: f64 = 1.5;

/// Documented coarse-mesh acceptance band on the lowest mode's `Re(k)`
/// vs the analytic TM_1,1 (observed ≈ 6.6 % on the small mesh).
const TM11_REL_TOL: f64 = 0.08;

/// Julia-vs-NumPy cross-IR floor — same rationale as the PML small
/// tiebreaker (LAPACK-vs-LAPACK measured ~1e-13; the wide gate
/// accommodates OpenBLAS build-variant drift across the Julia / Python
/// toolchain split without flapping).
const JULIA_NUMPY_ABS_TOL: f64 = 5.0e-3;

// ---------------------------------------------------------------------------
// Fixture paths
// ---------------------------------------------------------------------------

fn repo_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    for ancestor in manifest.ancestors() {
        if ancestor.join("reference").is_dir() {
            return ancestor.to_path_buf();
        }
    }
    panic!(
        "could not find a `reference/` directory walking up from {}",
        manifest.display()
    );
}

fn julia_fixture_path() -> PathBuf {
    repo_root().join("reference/fixtures/sphere_mie_small/julia_baseline.json")
}

fn numpy_fixture_path() -> PathBuf {
    repo_root().join("reference/fixtures/sphere_mie_small/baseline.json")
}

/// The small mesh is shared with the #158 sphere_pml_small fixture.
fn small_mesh_path() -> PathBuf {
    repo_root().join("reference/fixtures/sphere_pml_small/sphere.msh")
}

fn load_julia_fixture() -> Fixture {
    Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("sphere_mie_small/julia_baseline.json should load")
}

fn load_small_sphere_fixture() -> SphereFixture {
    let bytes = std::fs::read(small_mesh_path()).expect("read small-mesh sphere.msh bytes");
    read_sphere_fixture_from_bytes(&bytes).expect("parse small-mesh sphere.msh")
}

// ---------------------------------------------------------------------------
// Burn pipeline → complex (K_int, M_int) — same construction as
// sphere_mie_numpy_reference.rs (kept in lockstep).
// ---------------------------------------------------------------------------

struct BurnMiePipeline {
    n_nodes: usize,
    n_tets: usize,
    n_edges: usize,
    n_interior_edges: usize,
    spurious_dim: usize,
    epsilon_tensor_diag_flat: Vec<Complex64>,
    k_int_complex: faer::Mat<faer::c64>,
    m_int_complex: faer::Mat<faer::c64>,
}

fn run_burn_mie_pipeline(
    fixture: &SphereFixture,
    sigma_0: f64,
    n_index: f64,
    k0_ref: f64,
) -> BurnMiePipeline {
    let n_nodes = fixture.mesh.n_nodes();
    let n_tets = fixture.mesh.n_tets();

    let centroids = tet_centroids(&fixture.mesh);
    let eps_aniso = build_anisotropic_pml_tensor_diag(
        &fixture.tet_physical_tags,
        &centroids,
        n_index,
        sigma_0,
        k0_ref,
    );
    let epsilon_tensor_diag_flat: Vec<Complex64> = eps_aniso
        .iter()
        .flat_map(|row| row.iter().map(|c| Complex64::new(c.re, c.im)))
        .collect();

    let edges = fixture.mesh.edges();
    let n_edges = edges.len();
    let tet_edges = fixture.mesh.tet_edges();
    let tet_idx: Vec<[u32; 6]> = tet_edges
        .iter()
        .map(|row| std::array::from_fn(|i| row[i].0))
        .collect();
    let tet_sign: Vec<[i8; 6]> = tet_edges
        .iter()
        .map(|row| std::array::from_fn(|i| row[i].1))
        .collect();

    let (mask_edges, interior_mask) = sphere_pec_interior_edges(&fixture.mesh, R_BUFFER);
    assert_eq!(mask_edges.len(), n_edges, "Burn-side edge mask shape");
    let n_interior_edges = interior_mask.iter().filter(|&&b| b).count();
    let spurious_dim = sphere_n_interior_nodes(&fixture.mesh, R_BUFFER);

    let device = <B as BackendTypes>::Device::default();
    let (nodes_t, tets_t) = upload_mesh::<B>(&fixture.mesh, &device);
    let sys = assemble_global_nedelec_with_anisotropic_epsilon(
        nodes_t, tets_t, &tet_idx, &tet_sign, n_edges, &eps_aniso,
    );

    let k_full = burn_matrix_to_faer(sys.k);
    let m_complex_full = burn_complex_mass_to_faer(sys.m_re, sys.m_im);

    let dummy_zero = faer::Mat::<f64>::zeros(k_full.nrows(), k_full.ncols());
    let (k_int, _) = apply_dirichlet_bc(k_full.as_ref(), dummy_zero.as_ref(), &interior_mask)
        .expect("Dirichlet BC reduction (K)");

    let interior_idx: Vec<usize> = interior_mask
        .iter()
        .enumerate()
        .filter_map(|(i, &b)| if b { Some(i) } else { None })
        .collect();
    let dim = interior_idx.len();
    let m_int_complex = faer::Mat::<faer::c64>::from_fn(dim, dim, |i, j| {
        m_complex_full[(interior_idx[i], interior_idx[j])]
    });
    let k_int_complex =
        faer::Mat::<faer::c64>::from_fn(dim, dim, |i, j| faer::c64::new(k_int[(i, j)], 0.0));

    BurnMiePipeline {
        n_nodes,
        n_tets,
        n_edges,
        n_interior_edges,
        spurious_dim,
        epsilon_tensor_diag_flat,
        k_int_complex,
        m_int_complex,
    }
}

// ---------------------------------------------------------------------------
// λ → k and Q helpers — mirror of mie_sphere.rs / sphere_mie.py.
// ---------------------------------------------------------------------------

fn re_k_from_lambda(lambda: Complex64) -> f64 {
    let r = (lambda.re * lambda.re + lambda.im * lambda.im).sqrt();
    (0.5 * (r + lambda.re)).max(0.0).sqrt()
}

fn q_factor_from_lambda(lambda: Complex64) -> f64 {
    let r = (lambda.re * lambda.re + lambda.im * lambda.im).sqrt();
    let re_k = (0.5 * (r + lambda.re)).max(0.0).sqrt();
    let im_k_mag = (0.5 * (r - lambda.re)).max(0.0).sqrt();
    if im_k_mag > 1e-12 {
        re_k / (2.0 * im_k_mag)
    } else {
        f64::INFINITY
    }
}

fn input_scalar(fixture: &Fixture, name: &str) -> f64 {
    fixture.inputs[name].data.as_array().unwrap()[0]
        .as_f64()
        .unwrap()
}

fn output_scalar(fixture: &Fixture, name: &str) -> f64 {
    let f = fixture
        .output_f64(name)
        .unwrap_or_else(|e| panic!("fixture missing scalar output `{name}`: {e}"));
    assert_eq!(f.data.len(), 1, "scalar `{name}` should be length 1");
    f.data[0]
}

// ---------------------------------------------------------------------------
// Schema-level tests (no eigensolve)
// ---------------------------------------------------------------------------

#[test]
fn julia_mie_small_fixture_loads_with_expected_schema() {
    let fixture = load_julia_fixture();
    assert_eq!(
        fixture.fixture_id,
        "sphere_mie_small/n48_aniso_upml_mie_julia"
    );
    assert_eq!(fixture.schema_version, "1");

    for key in [
        "mesh_path",
        "sigma_0",
        "k0_ref",
        "r_sphere",
        "r_pml_inner",
        "r_buffer",
        "n_index",
        "epsilon_tensor_diag",
    ] {
        assert!(
            fixture.inputs.contains_key(key),
            "missing input field '{key}' in Julia sphere_mie_small fixture"
        );
    }
    assert_eq!(fixture.inputs["epsilon_tensor_diag"].dtype, "c128");
    assert_eq!(
        fixture.inputs["epsilon_tensor_diag"].shape.len(),
        2,
        "epsilon_tensor_diag should be declared (n_tets, 3)"
    );
    assert_eq!(fixture.inputs["epsilon_tensor_diag"].shape[1], 3);

    for key in [
        "n_nodes",
        "n_tets",
        "n_edges",
        "n_interior_edges",
        "spurious_dim",
        "n_spurious_observed",
        "eigenvalues_lowest_complex",
        "physical_eigenvalues_complex",
        "strict_mode_window_len",
        "analytic_tm11_k",
        "lowest_physical_re_k",
        "tm11_rel_err_lowest",
        "q_factor_lowest_physical",
        "q_median_tm11_triplet",
        "sigma_zero_lowest_physical_re",
    ] {
        assert!(
            fixture.outputs.contains_key(key),
            "missing output field '{key}' in Julia sphere_mie_small fixture"
        );
    }
    assert_eq!(fixture.outputs["eigenvalues_lowest_complex"].dtype, "c128");
    assert_eq!(
        fixture.outputs["physical_eigenvalues_complex"].dtype,
        "c128"
    );
    assert_eq!(fixture.outputs["q_factor_lowest_physical"].dtype, "f64");
}

#[test]
fn julia_mie_small_mesh_counts_match_small_mesh() {
    let fixture = load_julia_fixture();
    assert_eq!(output_scalar(&fixture, "n_nodes") as usize, 48);
    assert_eq!(output_scalar(&fixture, "n_tets") as usize, 197);
    assert_eq!(output_scalar(&fixture, "n_edges") as usize, 259);
    assert_eq!(output_scalar(&fixture, "n_interior_edges") as usize, 214);
    assert_eq!(output_scalar(&fixture, "spurious_dim") as usize, 31);
    assert_eq!(output_scalar(&fixture, "n_spurious_observed") as usize, 31);
}

#[test]
fn julia_mie_small_analytic_anchor_matches_burn_and_j1() {
    // The fixture re-exports the J.1 catalogue's TM_1,1 root; pin it
    // against the live Burn computation and the J.1 fixture.
    let fixture = load_julia_fixture();
    let anchor = output_scalar(&fixture, "analytic_tm11_k");

    let n_index = input_scalar(&fixture, "n_index");
    let analytic = merged_roots(n_index, &[1, 2, 3], R_SPHERE, R_BUFFER, 3);
    let ground = analytic
        .iter()
        .min_by(|a, b| a.k.partial_cmp(&b.k).unwrap())
        .expect("at least one analytic root");
    assert_eq!(ground.pol, MiePolarisation::TM);
    assert_eq!(ground.l, 1);
    assert_eq!(ground.n, 1);
    let err = (ground.k - anchor).abs();
    assert!(
        err < 1e-9,
        "Julia fixture analytic_tm11_k = {anchor} vs merged_roots TM_1,1 = {} (|Δ| = {err:.3e})",
        ground.k
    );

    let j1 = Fixture::load_from(
        &repo_root().join("reference/fixtures/mie_roots/baseline.json"),
        FixtureFormat::Json,
    )
    .expect("mie_roots baseline.json should load");
    let pols = j1.output_f64("root_pol").unwrap().data.clone();
    let ls = j1.output_f64("root_l").unwrap().data.clone();
    let ns = j1.output_f64("root_n").unwrap().data.clone();
    let ks = j1.output_f64("root_k").unwrap().data.clone();
    let tm11_j1 = (0..ks.len())
        .find(|&i| {
            pols[i].round() as i64 == 1 && ls[i].round() as i64 == 1 && ns[i].round() as i64 == 1
        })
        .map(|i| ks[i])
        .expect("TM_1,1 in the J.1 catalogue");
    assert!(
        (tm11_j1 - anchor).abs() < 1e-12,
        "Julia fixture analytic_tm11_k = {anchor} vs J.1 catalogue TM_1,1 = {tm11_j1}"
    );
}

#[test]
fn julia_mie_small_epsilon_tensor_matches_burn() {
    // The Julia-built diagonal UPML tensor must match Burn's
    // `build_anisotropic_pml_tensor_diag` at the f64 floor — pure host
    // math on both sides, no eigensolve.
    let fixture = load_julia_fixture();
    let golden_eps = fixture
        .input_c128("epsilon_tensor_diag")
        .expect("c128 input decodes");

    let sigma_0 = input_scalar(&fixture, "sigma_0");
    let n_index = input_scalar(&fixture, "n_index");
    let k0_ref = input_scalar(&fixture, "k0_ref");

    let sphere = load_small_sphere_fixture();
    let burn = run_burn_mie_pipeline(&sphere, sigma_0, n_index, k0_ref);
    assert_eq!(
        burn.epsilon_tensor_diag_flat.len(),
        golden_eps.len(),
        "tensor length mismatch (flattened (n_tets, 3))"
    );

    let mut max_abs = 0.0_f64;
    for (i, (got, want)) in burn
        .epsilon_tensor_diag_flat
        .iter()
        .zip(golden_eps.iter())
        .enumerate()
    {
        let err = (got - want).norm();
        if err > max_abs {
            max_abs = err;
        }
        assert!(
            err < 1.0e-14,
            "epsilon_tensor_diag[{i}]: |Δ| = {err:.3e} exceeds 1e-14 \
             (Burn = {got}, Julia = {want})"
        );
    }
    eprintln!(
        "sphere_mie_small Julia tensor: Burn vs Julia max |Δ| = {max_abs:.3e} \
         (anisotropic UPML tensor round-trips through c128 at f64 floor)"
    );
}

// ---------------------------------------------------------------------------
// Julia vs NumPy direct (no Burn eigensolve)
// ---------------------------------------------------------------------------

#[test]
fn julia_mie_small_agrees_with_numpy_at_full_scope() {
    // LAPACK ZGGEV (Julia) vs LAPACK ZGGEV (scipy) on the identical
    // tensor-ε pencil — measured ~1e-13; 5e-3 floor per the #160
    // tiebreaker rationale. Scope [0..4] (all 5 physical modes).
    let julia_fixture = load_julia_fixture();
    let numpy_fixture = Fixture::load_from(&numpy_fixture_path(), FixtureFormat::Json)
        .expect("NumPy sphere_mie_small baseline.json should load");

    let julia_phys = julia_fixture
        .output_c128("physical_eigenvalues_complex")
        .expect("Julia physical_eigenvalues_complex decodes");
    let numpy_phys = numpy_fixture
        .output_c128("physical_eigenvalues_complex")
        .expect("NumPy physical_eigenvalues_complex decodes");

    assert_eq!(julia_phys.data.len(), 5);
    assert_eq!(numpy_phys.data.len(), 5);

    let mut max_abs: f64 = 0.0;
    for (i, (lj, ln)) in julia_phys
        .data
        .iter()
        .zip(numpy_phys.data.iter())
        .enumerate()
    {
        let delta = (lj - ln).norm();
        max_abs = max_abs.max(delta);
        assert!(
            delta <= JULIA_NUMPY_ABS_TOL,
            "sphere_mie_small physical[{i}] cross-IR drift: Julia={lj:?}, \
             NumPy={ln:?}, |Δ| = {delta:.3e} > {JULIA_NUMPY_ABS_TOL:.0e}. Both \
             backends are LAPACK ZGGEV on the identical pencil; a large \
             residual means a regenerated fixture or a real toolchain drift."
        );
    }

    // σ₀ = 0 PEC anchors agree (same floor as the NumPy fixture's own
    // tolerance on this field).
    let julia_pec = output_scalar(&julia_fixture, "sigma_zero_lowest_physical_re");
    let numpy_pec = output_scalar(&numpy_fixture, "sigma_zero_lowest_physical_re");
    let pec_delta = (julia_pec - numpy_pec).abs();
    assert!(
        pec_delta < 5e-5,
        "σ₀=0 PEC anchor mismatch: Julia={julia_pec}, NumPy={numpy_pec}, \
         |Δ|={pec_delta:.3e} > 5e-5"
    );

    // Strict-window bookkeeping must agree too.
    assert_eq!(
        output_scalar(&julia_fixture, "strict_mode_window_len") as usize,
        output_scalar(&numpy_fixture, "strict_mode_window_len") as usize,
        "strict_mode_window_len drifted between the Julia and NumPy fixtures"
    );

    eprintln!(
        "Julia vs NumPy sphere_mie_small cross-IR check passed on scope [0..4]: \
         max |Δλ| = {max_abs:.3e} (tolerance {JULIA_NUMPY_ABS_TOL:.0e}); \
         σ₀=0 anchor |Δ| = {pec_delta:.3e}"
    );
}

// ---------------------------------------------------------------------------
// Burn vs Julia spectrum (default `cargo test` — ~214-DOF complex GEVD)
// ---------------------------------------------------------------------------

#[test]
fn julia_mie_small_spectrum_agrees_with_burn() {
    let fixture = load_julia_fixture();

    let sigma_0 = input_scalar(&fixture, "sigma_0");
    let n_index = input_scalar(&fixture, "n_index");
    let k0_ref = input_scalar(&fixture, "k0_ref");

    let sphere = load_small_sphere_fixture();
    let burn = run_burn_mie_pipeline(&sphere, sigma_0, n_index, k0_ref);

    // Mesh-shape integer cross-checks.
    assert_eq!(burn.n_nodes, output_scalar(&fixture, "n_nodes") as usize);
    assert_eq!(burn.n_tets, output_scalar(&fixture, "n_tets") as usize);
    assert_eq!(burn.n_edges, output_scalar(&fixture, "n_edges") as usize);
    assert_eq!(
        burn.n_interior_edges,
        output_scalar(&fixture, "n_interior_edges") as usize
    );
    assert_eq!(
        burn.spurious_dim,
        output_scalar(&fixture, "spurious_dim") as usize
    );

    // Solve the complex generalized tensor-ε pencil on the Burn side.
    let n_request = burn.spurious_dim + 8;
    let solver = FaerComplexEigensolver;
    let burn_eigvals_faer = solver
        .smallest_complex_pencil_eigenvalues(
            burn.k_int_complex.as_ref(),
            burn.m_int_complex.as_ref(),
            n_request,
        )
        .expect("Burn complex eigensolve on small Mie fixture");
    let burn_eigvals: Vec<Complex64> = burn_eigvals_faer
        .iter()
        .map(|c| Complex64::new(c.re, c.im))
        .collect();

    let golden_full = fixture
        .output_c128("eigenvalues_lowest_complex")
        .expect("c128 output decodes");
    assert_eq!(
        burn_eigvals.len(),
        golden_full.data.len(),
        "Burn returned {} eigenvalues, Julia baseline has {} — request mismatch",
        burn_eigvals.len(),
        golden_full.data.len()
    );

    let n_spurious_ref = output_scalar(&fixture, "n_spurious_observed") as usize;
    assert_eq!(n_spurious_ref, burn.spurious_dim);
    let golden_physical = fixture
        .output_c128("physical_eigenvalues_complex")
        .expect("c128 physical decodes");
    let physical_take = golden_physical.data.len();
    let burn_physical: Vec<Complex64> =
        burn_eigvals[n_spurious_ref..n_spurious_ref + physical_take].to_vec();

    // Full-slice + physical-band comparison via the c128 comparator
    // (per-field tolerances from the fixture: 5e-4 / 1e-4).
    let mut actual: BTreeMap<String, Vec<Complex64>> = BTreeMap::new();
    actual.insert(
        "eigenvalues_lowest_complex".to_string(),
        burn_eigvals.clone(),
    );
    actual.insert(
        "physical_eigenvalues_complex".to_string(),
        burn_physical.clone(),
    );
    let report = fixture.compare_complex_against(&actual);
    if !report.passed {
        eprintln!("sphere_mie_small Julia comparator report: {:#?}", report);
        panic!("Burn complex spectrum disagreed with the Julia small-mesh baseline");
    }

    // Strict cross-IR window (#160 cluster closure): the TM_1,1
    // triplet, closed at a spectral gap on the Burn side too.
    let window_len = output_scalar(&fixture, "strict_mode_window_len") as usize;
    assert!(window_len <= physical_take);
    let mut window_max = 0.0_f64;
    for (got, want) in burn_physical
        .iter()
        .zip(golden_physical.data.iter())
        .take(window_len)
    {
        window_max = window_max.max((got - want).norm());
    }
    let triplet_spread = burn_physical[window_len - 1].re - burn_physical[0].re;
    let gap_to_next = burn_physical[window_len].re - burn_physical[window_len - 1].re;
    assert!(
        gap_to_next > 2.0 * triplet_spread,
        "strict mode window does not end at a spectral gap on the Burn side \
         (spread = {triplet_spread:.4}, gap = {gap_to_next:.4}) — \
         cluster-closure convention (#160) violated"
    );

    // Small-mesh anisotropic-pencil sign: physical Im(λ) < 0 on both
    // sides (mesh-dependent — see PR #179 schema doc).
    for (i, (lam_burn, lam_julia)) in burn_physical
        .iter()
        .zip(golden_physical.data.iter())
        .take(window_len)
        .enumerate()
    {
        assert!(
            lam_burn.im <= 1e-10,
            "Burn physical[{i}] = {lam_burn} has Im(λ) > 0 — small-mesh \
             anisotropic UPML pencil carries Im(λ) < 0"
        );
        assert!(
            lam_julia.im <= 1e-10,
            "Julia physical[{i}] = {lam_julia:?} has Im(λ) > 0 — small-mesh \
             anisotropic UPML pencil carries Im(λ) < 0"
        );
    }

    // J.1 analytic anchor: lowest mode within the documented 8 % band
    // on both sides, and Burn-vs-Julia Re(k) within the fixture floor.
    let analytic_tm11_k = output_scalar(&fixture, "analytic_tm11_k");
    let burn_re_k = re_k_from_lambda(burn_physical[0]);
    let julia_re_k = output_scalar(&fixture, "lowest_physical_re_k");
    let burn_rel_err = (burn_re_k - analytic_tm11_k).abs() / analytic_tm11_k;
    let julia_rel_err = (julia_re_k - analytic_tm11_k).abs() / analytic_tm11_k;
    assert!(
        burn_rel_err < TM11_REL_TOL,
        "Burn lowest Re(k) = {burn_re_k:.5} differs from analytic TM_1,1 = \
         {analytic_tm11_k:.5} by {:.2}% (> {:.0}%)",
        burn_rel_err * 100.0,
        TM11_REL_TOL * 100.0
    );
    assert!(
        julia_rel_err < TM11_REL_TOL,
        "Julia lowest Re(k) = {julia_re_k:.5} differs from analytic TM_1,1 = \
         {analytic_tm11_k:.5} by {:.2}% (> {:.0}%)",
        julia_rel_err * 100.0,
        TM11_REL_TOL * 100.0
    );
    let re_k_delta = (burn_re_k - julia_re_k).abs();
    assert!(
        re_k_delta
            < fixture
                .output_f64("lowest_physical_re_k")
                .unwrap()
                .tolerance_abs,
        "Burn vs Julia lowest Re(k): |Δ| = {re_k_delta:.3e}"
    );

    // Q tripwire (Q_LOWER_BAND_TM11) on both sides + regression floor.
    let burn_q = q_factor_from_lambda(burn_physical[0]);
    let golden_q = fixture.output_f64("q_factor_lowest_physical").unwrap();
    let julia_q = golden_q.data[0];
    assert!(
        burn_q > Q_LOWER_BAND_TM11,
        "Burn lowest-mode Q = {burn_q:.3} below band {Q_LOWER_BAND_TM11}"
    );
    assert!(
        julia_q > Q_LOWER_BAND_TM11,
        "Julia lowest-mode Q = {julia_q:.3} below band {Q_LOWER_BAND_TM11}"
    );
    let q_err = (burn_q - julia_q).abs();
    assert!(
        q_err < golden_q.tolerance_abs,
        "q_factor_lowest_physical: Burn = {burn_q:.4}, Julia = {julia_q:.4}, \
         |Δ| = {q_err:.3e} exceeds {:.0e}",
        golden_q.tolerance_abs
    );

    eprintln!(
        "sphere_mie_small Burn vs Julia agreement: strict TM_1,1-triplet window \
         max |Δλ| = {window_max:.3e}; lowest Re(k): Burn {burn_re_k:.5} / Julia \
         {julia_re_k:.5} (analytic {analytic_tm11_k:.5}, rel err {:.2}% / {:.2}%); \
         Q: Burn {burn_q:.2} / Julia {julia_q:.2} (band > {Q_LOWER_BAND_TM11})",
        burn_rel_err * 100.0,
        julia_rel_err * 100.0
    );
}

// ---------------------------------------------------------------------------
// Comparator round-trip
// ---------------------------------------------------------------------------

#[test]
fn julia_mie_small_complex_comparator_self_round_trip() {
    let fixture = load_julia_fixture();

    let mut complex_actual: BTreeMap<String, Vec<Complex64>> = BTreeMap::new();
    for (name, output) in fixture.iter_outputs() {
        if output.dtype == "c128" {
            let g = fixture.output_c128(name).unwrap();
            complex_actual.insert(name.to_string(), g.data.clone());
        }
    }
    let report = fixture.compare_complex_against(&complex_actual);
    assert!(
        report.passed,
        "self-round-trip on c128 outputs should pass; report = {report:#?}"
    );
    for diff in &report.fields {
        assert!(
            matches!(diff.status, FieldStatus::Ok),
            "c128 field `{}` did not pass self-round-trip; status = {:?}",
            diff.field,
            diff.status
        );
        let max_err = diff.max_abs_error.expect("Ok diff carries max_abs_error");
        assert!(
            max_err < 1e-15,
            "c128 field `{}` self-round-trip |Δ| = {max_err:.3e} should be < 1e-15",
            diff.field
        );
    }
}
