//! Cross-IR sphere-PML loader/comparator against the Julia **small-mesh**
//! baseline (issue #160 — Option (b) resolution).
//!
//! Loads `reference/fixtures/sphere_pml/julia_small_baseline.json` (the Julia
//! reference for the vector-Nédélec sphere-PML eigenmode pipeline on the
//! 197-tet small-mesh fixture introduced in PR #164 / issue #158) and asserts:
//!
//! 1. **Schema conformance**: canonical v1 schema with the small-mesh-specific
//!    output field set (`physical_eigenvalues_complex`, `sigma_zero_lowest_physical_re`).
//! 2. **c128 round-trip**: `Fixture::output_c128` decodes the real-imag
//!    interleaved on-disk payload into `Vec<Complex64>`.
//! 3. **σ₀ = 0 PEC anchor**: `sigma_zero_lowest_physical_re` matches the
//!    canonical NumPy small-mesh baseline (PR #164) at 5e-5 absolute (the
//!    small mesh has no separate PEC baseline; the in-fixture anchor is
//!    the PEC regression).
//! 4. **σ₀ = 5 PML sign convention**: `physical_eigenvalues_complex` has
//!    `Im(λ) ≥ 0` per the Wave-2 canonical sign convention (PR #155).
//! 5. **Cross-IR scope [0..4] vs NumPy small-mesh baseline**: the Julia
//!    `physical_eigenvalues_complex` field agrees with the NumPy
//!    `physical_eigenvalues_complex` at **5e-3 absolute on `|Δ|`** for all 5
//!    modes — covering the **l=1 triplet** (positions [0..2]) and **2 of
//!    the l=2 quintuplet** (positions [3,4]). This is the resolution of
//!    PR #153 cycle 3's Arpack l=2-unreachability finding: dense Julia
//!    eigen on the small mesh surfaces both bands cleanly.
//!
//! # Why this test exists
//!
//! The companion `sphere_pml_julia_reference.rs` test (full mesh, 3300-DOF
//! pencil) restricts its strict cross-IR scope to positions [0..2] because
//! the full-mesh path uses Arpack shift-invert at σ = 1.18 + 0.21j, which
//! saturates within the l=1 lossy cluster and never reaches the l=2
//! quintuplet (canonical NumPy positions [3,4]). This small-mesh sibling
//! resolves issue #160 by switching to dense `LinearAlgebra.eigen(K, M)`
//! on the 214-DOF interior pencil — see
//! `reference/julia/sphere_pml_small.jl` for the design rationale.
//!
//! Both backends (Julia and NumPy) here use LAPACK ZGGEV on the identical
//! complex-symmetric pencil, so agreement is expected at LAPACK-vs-LAPACK
//! roundoff (~1e-13 measured); 5e-3 is the conservative floor accommodating
//! Julia OpenBLAS vs scipy OpenBLAS reduction-order variance across the
//! Julia / Python toolchain split.
//!
//! # Running
//!
//! ```sh
//! cargo test -p geode-validation --test sphere_pml_julia_small_reference
//! ```

use std::collections::BTreeMap;
use std::path::PathBuf;

use geode_validation::diff::FieldStatus;
use geode_validation::{Complex64, Fixture, FixtureFormat};

/// Walk up from `CARGO_MANIFEST_DIR` to find the repo root.
fn repo_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    for ancestor in manifest.ancestors() {
        if ancestor.join("reference").is_dir() {
            return ancestor.to_path_buf();
        }
    }
    panic!(
        "could not find `reference/` directory walking up from {}",
        manifest.display()
    );
}

/// The Julia small-mesh baseline, generated by
/// `reference/julia/gen_sphere_pml_small_baseline.jl`.
fn julia_fixture_path() -> PathBuf {
    repo_root().join("reference/fixtures/sphere_pml/julia_small_baseline.json")
}

/// The NumPy small-mesh canonical baseline (PR #164, issue #158).
fn numpy_small_fixture_path() -> PathBuf {
    repo_root().join("reference/fixtures/sphere_pml_small/baseline.json")
}

// ---------------------------------------------------------------------------
// Schema + loader smoke
// ---------------------------------------------------------------------------

#[test]
fn julia_pml_small_fixture_loads_with_canonical_schema() {
    let fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");
    assert_eq!(
        fixture.fixture_id,
        "sphere_pml_small/n48_pml_eigenmode_julia"
    );
    assert_eq!(fixture.schema_version, "1");

    // Required input fields.
    for key in [
        "mesh_path",
        "sigma_0",
        "r_sphere",
        "r_pml_inner",
        "r_buffer",
        "n_index",
        "epsilon_r_complex",
    ] {
        assert!(
            fixture.inputs.contains_key(key),
            "Julia small-mesh PML fixture missing required input `{key}`"
        );
    }
    assert_eq!(
        fixture.inputs["epsilon_r_complex"].dtype, "c128",
        "epsilon_r_complex must be c128 (the input-side complex contract)"
    );

    // Required output fields — matches the NumPy small-mesh schema.
    for key in [
        "n_nodes",
        "n_tets",
        "n_edges",
        "n_interior_edges",
        "spurious_dim",
        "n_spurious_observed",
        "k_int_frobenius_complex",
        "m_int_frobenius_complex",
        "eigenvalues_lowest_complex",
        "physical_eigenvalues_complex",
        "q_factor_lowest_physical",
        "sigma_zero_lowest_physical_re",
    ] {
        assert!(
            fixture.outputs.contains_key(key),
            "Julia small-mesh PML fixture missing required output `{key}`"
        );
    }
    assert_eq!(
        fixture.outputs["eigenvalues_lowest_complex"].dtype, "c128",
        "eigenvalues_lowest_complex must be c128"
    );
    assert_eq!(
        fixture.outputs["physical_eigenvalues_complex"].dtype, "c128",
        "physical_eigenvalues_complex must be c128"
    );
    assert_eq!(
        fixture.outputs["q_factor_lowest_physical"].dtype, "f64",
        "q_factor_lowest_physical is a real-valued derived metric"
    );
    assert_eq!(
        fixture.outputs["sigma_zero_lowest_physical_re"].dtype, "f64",
        "sigma_zero_lowest_physical_re is the PEC anchor"
    );
}

#[test]
fn julia_pml_small_fixture_mesh_counts_match_small_mesh() {
    let fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");

    // Small-mesh counts — match the canonical NumPy small-mesh
    // baseline (PR #164 / issue #158).
    let n_nodes = fixture.output_f64("n_nodes").unwrap().data[0];
    let n_tets = fixture.output_f64("n_tets").unwrap().data[0];
    let n_edges = fixture.output_f64("n_edges").unwrap().data[0];
    let n_int = fixture.output_f64("n_interior_edges").unwrap().data[0];
    let spurious_dim = fixture.output_f64("spurious_dim").unwrap().data[0];
    let n_sp_observed = fixture.output_f64("n_spurious_observed").unwrap().data[0];

    assert_eq!(n_nodes as usize, 48, "n_nodes (small sphere mesh)");
    assert_eq!(n_tets as usize, 197, "n_tets (small sphere mesh)");
    assert_eq!(n_edges as usize, 259, "n_edges (small sphere mesh)");
    assert_eq!(
        n_int as usize, 214,
        "n_interior_edges (small mesh PEC reduction)"
    );
    assert_eq!(
        spurious_dim as usize, 31,
        "spurious_dim (small mesh interior nodes)"
    );
    assert_eq!(
        n_sp_observed as usize, 31,
        "n_spurious_observed (small mesh d⁰ rank)"
    );
}

// ---------------------------------------------------------------------------
// c128 round-trip
// ---------------------------------------------------------------------------

#[test]
fn julia_pml_small_epsilon_r_complex_decodes_to_n_tets_length() {
    let fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");

    let eps = fixture
        .input_c128("epsilon_r_complex")
        .expect("c128 input decodes");
    assert_eq!(
        eps.len(),
        197,
        "epsilon_r_complex must have length n_tets = 197"
    );

    // The dielectric region: ε_r = n² = 2.25 (purely real).
    let n_dielectric = eps
        .iter()
        .filter(|c| (c.re - 2.25).abs() < 1e-12 && c.im.abs() < 1e-12)
        .count();
    assert!(
        n_dielectric > 0,
        "expected at least one dielectric tet with ε_r = 2.25 + 0j, found 0"
    );

    // The PML shell: Im(ε_r) < 0 (PML absorption signature).
    let n_pml = eps.iter().filter(|c| c.im < -1e-6).count();
    assert!(
        n_pml > 0,
        "expected PML-shell tets with Im(ε_r) < 0, found 0"
    );

    // Vacuum gap.
    let n_vacuum = eps
        .iter()
        .filter(|c| (c.re - 1.0).abs() < 1e-12 && c.im.abs() < 1e-12)
        .count();
    assert!(
        n_vacuum > 0,
        "expected vacuum-gap tets with ε_r = 1 + 0j, found 0"
    );

    assert_eq!(
        n_dielectric + n_pml + n_vacuum,
        197,
        "dielectric + PML + vacuum partition must cover all 197 tets"
    );
}

#[test]
fn julia_pml_small_physical_eigenvalues_complex_decodes() {
    let fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");

    let phys = fixture
        .output_c128("physical_eigenvalues_complex")
        .expect("c128 output decodes");
    assert_eq!(
        phys.numel(),
        5,
        "physical_eigenvalues_complex declares shape [5]"
    );
    assert_eq!(phys.data.len(), 5);

    // Every entry must be finite.
    for (i, lam) in phys.data.iter().enumerate() {
        assert!(
            lam.re.is_finite() && lam.im.is_finite(),
            "physical_eigenvalues_complex[{i}] = {lam:?} is not finite"
        );
    }
}

// ---------------------------------------------------------------------------
// Physical content checks
// ---------------------------------------------------------------------------

#[test]
fn julia_pml_small_sigma_zero_matches_numpy_pec_anchor() {
    // The σ₀=0 PEC anchor (`sigma_zero_lowest_physical_re`) must match
    // the canonical NumPy small-mesh baseline. Both backends use LAPACK
    // on the same real-symmetric pencil at σ₀=0; the agreement is
    // expected at LAPACK-vs-LAPACK roundoff (~1e-13 measured).
    //
    // Tolerance is 5e-5 — matches the NumPy fixture's own
    // `sigma_zero_lowest_physical_re` tolerance_abs (the PR #164 floor
    // for faer-vs-LAPACK on the small mesh; Julia-vs-LAPACK is much
    // tighter but uses the same defensible bound).
    let julia_fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");
    let numpy_fixture = Fixture::load_from(&numpy_small_fixture_path(), FixtureFormat::Json)
        .expect("NumPy small-mesh baseline.json should load");

    let julia_pec_re = julia_fixture
        .output_f64("sigma_zero_lowest_physical_re")
        .unwrap()
        .data[0];
    let numpy_pec_re = numpy_fixture
        .output_f64("sigma_zero_lowest_physical_re")
        .unwrap()
        .data[0];

    let delta = (julia_pec_re - numpy_pec_re).abs();
    assert!(
        delta < 5e-5,
        "σ₀=0 PEC anchor mismatch: Julia={julia_pec_re}, NumPy={numpy_pec_re}, |Δ|={delta:.3e} > 5e-5"
    );
}

#[test]
fn julia_pml_small_sigma_five_has_pml_absorption_signature() {
    // Physical-content correctness: with σ₀ = 5, all lowest physical
    // modes must have Im(λ) ≥ 0 under the Wave-2 canonical sign
    // convention (PR #155 Judge's binding decision).
    let fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");

    let phys = fixture
        .output_c128("physical_eigenvalues_complex")
        .expect("c128 output decodes");
    let q = fixture.output_f64("q_factor_lowest_physical").unwrap().data[0];

    for (i, lam) in phys.data.iter().enumerate() {
        assert!(
            lam.im >= -1e-6,
            "physical[{i}] = {lam:?} has Im(λ) < 0 — sign-convention regression \
             (Wave-2 canonical: Im(λ) > 0 per PR #155)"
        );
    }

    // Q-factor must be finite and positive. On the small mesh's coarse
    // discretization the ground mode is high-Q (~34.8).
    assert!(q.is_finite(), "Q-factor must be finite, got {q}");
    assert!(
        q > 0.0,
        "Q-factor for the lowest physical mode must be positive (PML absorption), got {q}"
    );

    // Re(λ) for the canonical small-mesh physical[0] is ≈ 1.92 (vs
    // the full mesh's ≈ 1.18). Loose sanity bound [1.5, 2.5].
    let re_lowest = phys.data[0].re;
    assert!(
        (1.5..2.5).contains(&re_lowest),
        "Re(λ_lowest_physical) = {re_lowest} outside [1.5, 2.5] sanity band \
         for σ₀=5 small-mesh PML — expected canonical band around 1.92"
    );
}

// ---------------------------------------------------------------------------
// Cross-IR scope [0..4] vs NumPy
// ---------------------------------------------------------------------------

#[test]
fn julia_pml_small_sigma_five_agrees_with_numpy_at_full_scope() {
    // **Issue #160 acceptance criterion — strict scope [0..4]**.
    //
    // The Julia small-mesh dense `LinearAlgebra.eigen(K, M)` path and
    // the NumPy `scipy.linalg.eigvals` path both call LAPACK ZGGEV on
    // the identical 214×214 complex-symmetric pencil; the agreement is
    // expected at LAPACK-vs-LAPACK roundoff (~1e-13 measured) with
    // headroom for OpenBLAS reduction-order variance across the Julia
    // / Python toolchain split.
    //
    // This test cross-checks **all 5 physical modes** (l=1 triplet
    // [0..2] at λ ≈ 1.92 + 0.06j + 2 of l=2 quintuplet [3,4] at
    // λ ≈ 3.28 + 0.15j and 3.57 + 0.12j) at **5e-3 absolute on `|Δ|`**.
    //
    // 5e-3 is conservative — measured residual is 1.3e-13. The wider
    // gate accommodates downstream Julia stdlib upgrades and OpenBLAS
    // build-variant differences without flapping. The actual fixture
    // tolerance on `physical_eigenvalues_complex` is also 5e-3 (set
    // in the generator).
    //
    // This is the **resolution of PR #153 cycle 3's Arpack
    // l=2-unreachability finding** (issue #160): the full-mesh Arpack
    // shift-invert at σ = 1.18 + 0.21j saturates within the l=1 cluster
    // and never reaches l=2 even at nev = 105. The small-mesh dense
    // path surfaces both bands cleanly with no shift-invert
    // basin-of-attraction concerns. The full-mesh
    // `sphere_pml_julia_reference.rs` test (currently scope [0..2])
    // stays as-is — extending its scope is out of scope for #160 and
    // would require either Option (a) multi-shift Arpack or a follow-up
    // issue.
    let julia_fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");
    let numpy_fixture = Fixture::load_from(&numpy_small_fixture_path(), FixtureFormat::Json)
        .expect("NumPy small-mesh baseline.json should load");

    let julia_phys = julia_fixture
        .output_c128("physical_eigenvalues_complex")
        .expect("Julia physical_eigenvalues_complex decodes");
    let numpy_phys = numpy_fixture
        .output_c128("physical_eigenvalues_complex")
        .expect("NumPy physical_eigenvalues_complex decodes");

    assert_eq!(
        julia_phys.data.len(),
        5,
        "Julia must declare 5 physical modes (l=1 triplet + 2 of l=2 quintuplet)"
    );
    assert_eq!(
        numpy_phys.data.len(),
        5,
        "NumPy must declare 5 physical modes"
    );

    let abs_tol: f64 = 5.0e-3;
    let mut max_abs: f64 = 0.0;
    let mut max_idx: usize = 0;

    // **Strict scope [0..4]** — the full set of 5 physical modes.
    for (i, (lj, ln)) in julia_phys
        .data
        .iter()
        .zip(numpy_phys.data.iter())
        .enumerate()
    {
        let delta = (lj - ln).norm();
        if delta > max_abs {
            max_abs = delta;
            max_idx = i;
        }
        assert!(
            delta <= abs_tol,
            "small-mesh physical[{i}] cross-IR drift: Julia={lj:?}, NumPy={ln:?}, \
             |Δ| = {delta:.3e} > {abs_tol:.0e}. Both backends use LAPACK ZGGEV \
             on the identical pencil; a large residual here means either the \
             Julia path stopped using dense LinearAlgebra.eigen, the NumPy \
             fixture was regenerated against a different mesh, or there's a \
             real LAPACK ABI drift to investigate."
        );
    }

    eprintln!(
        "Julia vs NumPy small-mesh sphere-PML cross-IR check passed on \
         **scope [0..4]** (all 5 physical modes — l=1 triplet + 2 of l=2 \
         quintuplet): max |Δ| = {max_abs:.3e} at position [{max_idx}], \
         tolerance = {abs_tol:.0e}. This is the issue #160 Option (b) \
         resolution of PR #153 cycle 3's Arpack l=2-unreachability finding."
    );
}

// ---------------------------------------------------------------------------
// Comparator round-trip
// ---------------------------------------------------------------------------

#[test]
fn julia_pml_small_complex_comparator_self_round_trip() {
    let fixture = Fixture::load_from(&julia_fixture_path(), FixtureFormat::Json)
        .expect("julia_small_baseline.json should load");

    let mut complex_actual: BTreeMap<String, Vec<Complex64>> = BTreeMap::new();
    for (name, output) in fixture.iter_outputs() {
        if output.dtype == "c128" {
            let g = fixture.output_c128(name).unwrap();
            complex_actual.insert(name.to_string(), g.data.clone());
        }
    }
    let report = fixture.compare_complex_against(&complex_actual);
    assert!(
        report.passed,
        "self-round-trip on c128 outputs should pass; report = {report:#?}"
    );
    for diff in &report.fields {
        assert!(
            matches!(diff.status, FieldStatus::Ok),
            "c128 field `{}` did not pass self-round-trip; status = {:?}",
            diff.field,
            diff.status
        );
        let max_err = diff.max_abs_error.expect("Ok diff carries max_abs_error");
        assert!(
            max_err < 1e-15,
            "c128 field `{}` self-round-trip |Δ| = {max_err:.3e} should be < 1e-15",
            diff.field
        );
    }
}
