//! Bundled transmon + readout-resonator mesh fixture + tag adapter
//! (Epic #476 Phase A, issue #485).
//!
//! Ingests the DeviceLayout.jl `SingleTransmon` geometry — the AWS
//! `aws-cqc/DeviceLayout.jl` transmon benchmark — into the same
//! surface-group-aware form the eigen/driven machinery already consumes
//! (mirrors [`super::spiral`] / [`super::patch`]). Phase A delivers mesh
//! ingestion only: a coarse smoke solve **runs** on this fixture; the
//! quantitative eigenfrequency comparison against the Palace oracle is
//! Phase B.
//!
//! # Fixture provenance (real vs placeholder)
//!
//! The real mesh is generated **offline** by
//! `reference/julia/generate_transmon_fixture.jl` (Julia + DeviceLayout.jl
//! are NOT geode-fem CI dependencies — same offline policy as the spiral
//! and patch fixtures). DeviceLayout.jl cannot currently be loaded in the
//! Loom build environment (its `backends/graphics.jl` pulls in Cairo,
//! which fails to precompile: `UndefVarError: libpango`), so the bundled
//! `transmon_smoke.msh` is a schema-faithful **PLACEHOLDER** generated by
//! `reference/gmsh/generate_transmon_placeholder.py` from
//! `reference/gmsh/transmon_placeholder.geo`: two coplanar transmon pads
//! with a junction square, a readout trace, and two readout-port squares
//! on a sapphire slab in a vacuum box. It carries the **identical
//! physical-group names** the real fixture uses, so it is a drop-in swap
//! target — this adapter and its tests are unchanged when the operator
//! swaps in the real mesh (only the per-group element-count assertions in
//! `tests/transmon_mesh.rs` update, from the new provenance file). The
//! provenance file records `kind: PLACEHOLDER` until then.
//!
//! # Physical groups
//!
//! The seven groups the (non-wave-port) DeviceLayout Palace config
//! consumes, verified against the installed DeviceLayout v1.15.0
//! `examples/SingleTransmon/SingleTransmon.jl`:
//!
//! | dim | tag | name                | meaning                                     |
//! |-----|-----|---------------------|---------------------------------------------|
//! | 3   | 1   | `substrate`         | sapphire chip slab                          |
//! | 3   | 2   | `vacuum`            | vacuum box above/around the chip            |
//! | 2   | 11  | `metal`             | PEC (ground + pads + trace + readout line)  |
//! | 2   | 12  | `port_1`            | lumped port, R = 50 Ω, Direction +X         |
//! | 2   | 13  | `port_2`            | lumped port, R = 50 Ω, Direction +X         |
//! | 2   | 14  | `lumped_element`    | junction port, L = 14.860 nH, C = 5.5 fF, +Y|
//! | 2   | 15  | `exterior_boundary` | far-field wall (first-order Absorbing)      |
//!
//! Keep this table in sync with `reference/julia/generate_transmon_fixture.jl`
//! and `reference/gmsh/transmon_placeholder.geo`.
//!
//! # Sapphire material model (rotated anisotropic tensor)
//!
//! The substrate is **sapphire, anisotropic AND rotated**: the Palace
//! config sets `Permittivity = [9.3, 9.3, 11.5]` with
//! `MaterialAxes = [[0.8,0.6,0.0], [-0.6,0.8,0.0], [0.0,0.0,1.0]]`, a
//! ~36.87° in-plane rotation. The lab-frame tensor is therefore
//! `R · diag(9.3, 9.3, 11.5) · Rᵀ` with off-diagonal xy-coupling — NOT
//! the diagonal tensor. [`sapphire_eps_lab`] returns that rotated tensor;
//! [`TransmonFixture::epsilon_tensor_r`] emits the per-tet 3×3 ε map
//! (rotated tensor on substrate tets, identity on vacuum) ready for
//! [`crate::assembly::nedelec::assemble_global_nedelec_with_full_tensors`]
//! — the full-tensor eigenmode path already proven by
//! `tests/sphere_matched_upml_eigenmode.rs`. Phase B composes that
//! assembler with the transmon tag layout; no new tensor plumbing is
//! needed.
//!
//! For the **Phase-A smoke solve** the isotropic hook
//! [`TransmonFixture::epsilon_r_scalar`] uses the trace-averaged scalar
//! `ε̄ = (9.3 + 9.3 + 11.5) / 3` on the substrate (the rotation is
//! trace-invariant, so the average is orientation-independent) and 1 in
//! vacuum. Upstream also specifies μ_r ≈ 1 ([`SAPPHIRE_MU_DIAG`],
//! negligible) and a loss tangent ([`SAPPHIRE_LOSS_TAN`]) — recorded here
//! for Phase B, unused in the lossless smoke run.

use faer::c64;

use super::msh_tags::{parse_elements_with_entity_tags, parse_entities_physical_tags};
use super::{GmshReader, MeshError, MeshReader, TetMesh};
use crate::driven::ports::LumpedPort;

/// Physical-group tag for the sapphire chip slab (3D).
pub const PHYS_SUBSTRATE: i32 = 1;
/// Physical-group tag for the vacuum box (3D).
pub const PHYS_VACUUM: i32 = 2;
/// Physical-group tag for the PEC metal surfaces (2D).
pub const PHYS_METAL: i32 = 11;
/// Physical-group tag for readout lumped port 1 (2D).
pub const PHYS_PORT_1: i32 = 12;
/// Physical-group tag for readout lumped port 2 (2D).
pub const PHYS_PORT_2: i32 = 13;
/// Physical-group tag for the junction lumped-element port (2D).
pub const PHYS_LUMPED_ELEMENT: i32 = 14;
/// Physical-group tag for the far-field exterior boundary (2D).
pub const PHYS_EXTERIOR_BOUNDARY: i32 = 15;

/// Sapphire relative-permittivity principal values `[ε₁, ε₂, ε₃]` in the
/// crystal frame (DeviceLayout `Permittivity = [9.3, 9.3, 11.5]`).
pub const SAPPHIRE_EPS_DIAG: [f64; 3] = [9.3, 9.3, 11.5];

/// In-plane crystal-axis rotation `R` (rows are the `MaterialAxes` from
/// the DeviceLayout config: `[[0.8,0.6,0], [-0.6,0.8,0], [0,0,1]]`), a
/// ~36.87° rotation about `z`. The lab-frame ε tensor is `R·diag·Rᵀ`.
pub const SAPPHIRE_MATERIAL_AXES: [[f64; 3]; 3] =
    [[0.8, 0.6, 0.0], [-0.6, 0.8, 0.0], [0.0, 0.0, 1.0]];

/// Sapphire relative-permeability principal values (DeviceLayout
/// `Permeability = [0.99999975, 0.99999975, 0.99999979]`). ≈ 1 — recorded
/// for Phase B provenance, treated as `μ_r = 1` in Phase A.
pub const SAPPHIRE_MU_DIAG: [f64; 3] = [0.99999975, 0.99999975, 0.99999979];

/// Sapphire loss tangent (DeviceLayout `LossTan = [3.0e-5, 3.0e-5,
/// 8.6e-5]`). Irrelevant for the lossless eigenmode smoke run — recorded
/// for Phase B Q-factor work.
pub const SAPPHIRE_LOSS_TAN: [f64; 3] = [3.0e-5, 3.0e-5, 8.6e-5];

/// Readout lumped-port resistance `R = 50 Ω` (DeviceLayout config). Given
/// here in ohms; convert to natural units (η₀) at solve time.
pub const PORT_RESISTANCE_OHM: f64 = 50.0;

/// Junction lumped-element inductance `L = 14.860 nH` (DeviceLayout
/// config) — the landing zone for Phase B's lumped-inductance BC.
pub const JUNCTION_INDUCTANCE_H: f64 = 14.860e-9;

/// Junction lumped-element capacitance `C = 5.5 fF` (DeviceLayout config).
pub const JUNCTION_CAPACITANCE_F: f64 = 5.5e-15;

/// Readout-port field direction `ê = +X` (DeviceLayout `Direction "+X"`).
pub const PORT_E_HAT: [f64; 3] = [1.0, 0.0, 0.0];

/// Junction-port field direction `ê = +Y` (DeviceLayout `Direction
/// "+Y"`).
pub const JUNCTION_E_HAT: [f64; 3] = [0.0, 1.0, 0.0];

/// Lab-frame sapphire permittivity tensor `R · diag(ε) · Rᵀ`, computed
/// from [`SAPPHIRE_EPS_DIAG`] and [`SAPPHIRE_MATERIAL_AXES`]. The in-plane
/// rotation produces off-diagonal `xy` coupling; the `zz` entry is
/// unchanged (11.5) because the rotation is about `z`.
pub fn sapphire_eps_lab() -> [[f64; 3]; 3] {
    let r = SAPPHIRE_MATERIAL_AXES;
    let d = SAPPHIRE_EPS_DIAG;
    // (R · diag(d) · Rᵀ)[i][j] = Σ_k R[i][k] d[k] R[j][k].
    let mut out = [[0.0_f64; 3]; 3];
    for (i, oi) in out.iter_mut().enumerate() {
        for (j, oij) in oi.iter_mut().enumerate() {
            let mut s = 0.0;
            for k in 0..3 {
                s += r[i][k] * d[k] * r[j][k];
            }
            *oij = s;
        }
    }
    out
}

/// Trace-averaged isotropic sapphire permittivity
/// `ε̄ = (ε₁ + ε₂ + ε₃) / 3`. The trace is rotation-invariant, so this is
/// orientation-independent — the scalar hook for the Phase-A smoke solve.
pub fn sapphire_eps_scalar() -> f64 {
    SAPPHIRE_EPS_DIAG.iter().sum::<f64>() / 3.0
}

/// Raw bytes of the bundled coarse transmon **smoke** fixture (MSH 4.1
/// ASCII). Currently a schema-faithful PLACEHOLDER (see module docs).
const TRANSMON_SMOKE_MSH: &[u8] = include_bytes!("../../tests/fixtures/transmon_smoke.msh");

/// Loaded transmon mesh fixture: volume mesh plus per-element
/// region/surface tags (same shape as [`super::SpiralFixture`] /
/// [`super::PatchFixture`]).
#[derive(Clone, Debug)]
pub struct TransmonFixture {
    /// Volume mesh (nodes + tets + physical-group dictionary).
    pub mesh: TetMesh,
    /// Per-tet 3D physical tag (parallel to `mesh.tets`).
    pub tet_physical_tags: Vec<i32>,
    /// Tagged surface triangles (0-based node indices into `mesh.nodes`):
    /// metal, the three ports, and the exterior boundary.
    pub boundary_triangles: Vec<[u32; 3]>,
    /// Per-triangle 2D physical tag (parallel to `boundary_triangles`).
    pub triangle_physical_tags: Vec<i32>,
}

impl TransmonFixture {
    /// Triangles carrying the given 2D physical tag.
    pub fn triangles_with_tag(&self, tag: i32) -> Vec<[u32; 3]> {
        self.boundary_triangles
            .iter()
            .zip(self.triangle_physical_tags.iter())
            .filter_map(|(tri, &t)| if t == tag { Some(*tri) } else { None })
            .collect()
    }

    /// Metal PEC faces (tag [`PHYS_METAL`]) — feed to
    /// [`super::spiral::pec_interior_mask_from_triangles`] for the PEC
    /// edge mask.
    pub fn metal_triangles(&self) -> Vec<[u32; 3]> {
        self.triangles_with_tag(PHYS_METAL)
    }

    /// Readout port-1 faces (tag [`PHYS_PORT_1`]).
    pub fn port_1_triangles(&self) -> Vec<[u32; 3]> {
        self.triangles_with_tag(PHYS_PORT_1)
    }

    /// Readout port-2 faces (tag [`PHYS_PORT_2`]).
    pub fn port_2_triangles(&self) -> Vec<[u32; 3]> {
        self.triangles_with_tag(PHYS_PORT_2)
    }

    /// Junction lumped-element port faces (tag [`PHYS_LUMPED_ELEMENT`]) —
    /// the tagged surface for Phase B's lumped-inductance BC (this issue
    /// delivers the surface, not the BC).
    pub fn lumped_element_triangles(&self) -> Vec<[u32; 3]> {
        self.triangles_with_tag(PHYS_LUMPED_ELEMENT)
    }

    /// Exterior-boundary faces (tag [`PHYS_EXTERIOR_BOUNDARY`]) — the
    /// far-field wall (PEC or absorbing at solve time — solver choice out
    /// of scope here).
    pub fn exterior_boundary_triangles(&self) -> Vec<[u32; 3]> {
        self.triangles_with_tag(PHYS_EXTERIOR_BOUNDARY)
    }

    /// 0-based tet indices (into `mesh.tets`) carrying the given 3D
    /// physical tag.
    pub fn tets_with_tag(&self, tag: i32) -> Vec<u32> {
        self.tet_physical_tags
            .iter()
            .enumerate()
            .filter_map(|(i, &t)| if t == tag { Some(i as u32) } else { None })
            .collect()
    }

    /// Substrate (sapphire) tets (tag [`PHYS_SUBSTRATE`]).
    pub fn substrate_tets(&self) -> Vec<u32> {
        self.tets_with_tag(PHYS_SUBSTRATE)
    }

    /// Vacuum tets (tag [`PHYS_VACUUM`]).
    pub fn vacuum_tets(&self) -> Vec<u32> {
        self.tets_with_tag(PHYS_VACUUM)
    }

    /// Per-tet complex relative permittivity from a tag → ε map.
    pub fn epsilon_r_by_tag(&self, f: impl Fn(i32) -> c64) -> Vec<c64> {
        self.tet_physical_tags.iter().map(|&t| f(t)).collect()
    }

    /// Per-tet **scalar** relative permittivity for the Phase-A smoke
    /// solve: the trace-averaged sapphire scalar [`sapphire_eps_scalar`]
    /// on substrate tets, `ε_r = 1` in vacuum. Real-valued (lossless).
    pub fn epsilon_r_scalar(&self) -> Vec<f64> {
        let eps_sub = sapphire_eps_scalar();
        self.tet_physical_tags
            .iter()
            .map(|&t| if t == PHYS_SUBSTRATE { eps_sub } else { 1.0 })
            .collect()
    }

    /// Per-tet **full 3×3** relative-permittivity tensor for Phase B: the
    /// rotated lab-frame sapphire tensor [`sapphire_eps_lab`] on substrate
    /// tets, the identity on vacuum tets. Real diagonal + off-diagonal
    /// `xy` coupling; imaginary part zero (lossless — the loss tangent is
    /// applied separately for Q-factor work). Shape matches
    /// [`crate::assembly::nedelec::assemble_global_nedelec_with_full_tensors`]'s
    /// `epsilon_tensor` argument.
    pub fn epsilon_tensor_r(&self) -> Vec<[[c64; 3]; 3]> {
        let lab = sapphire_eps_lab();
        let sub: [[c64; 3]; 3] =
            std::array::from_fn(|i| std::array::from_fn(|j| c64::new(lab[i][j], 0.0)));
        let identity: [[c64; 3]; 3] = std::array::from_fn(|i| {
            std::array::from_fn(|j| c64::new(if i == j { 1.0 } else { 0.0 }, 0.0))
        });
        self.tet_physical_tags
            .iter()
            .map(|&t| if t == PHYS_SUBSTRATE { sub } else { identity })
            .collect()
    }

    /// Build a lumped-port adapter from a tagged port face set with a
    /// given direction `ê`. The gap `length` (extent along `ê`) and
    /// effective `width` (area / length) are derived from the tagged
    /// triangles, tracking the geometry without duplicating parameters.
    fn port_from_tag(&self, tag: i32, e_hat: [f64; 3]) -> TransmonPort {
        let faces = self.triangles_with_tag(tag);
        assert!(
            !faces.is_empty(),
            "transmon fixture carries no triangles for port tag {tag}"
        );

        let (mut lo, mut hi) = (f64::INFINITY, f64::NEG_INFINITY);
        let mut area = 0.0_f64;
        for tri in &faces {
            let v: [[f64; 3]; 3] = std::array::from_fn(|k| self.mesh.nodes[tri[k] as usize]);
            for p in &v {
                let along = p[0] * e_hat[0] + p[1] * e_hat[1] + p[2] * e_hat[2];
                lo = lo.min(along);
                hi = hi.max(along);
            }
            let e1 = [v[1][0] - v[0][0], v[1][1] - v[0][1], v[1][2] - v[0][2]];
            let e2 = [v[2][0] - v[0][0], v[2][1] - v[0][1], v[2][2] - v[0][2]];
            let cx = e1[1] * e2[2] - e1[2] * e2[1];
            let cy = e1[2] * e2[0] - e1[0] * e2[2];
            let cz = e1[0] * e2[1] - e1[1] * e2[0];
            area += 0.5 * (cx * cx + cy * cy + cz * cz).sqrt();
        }
        // Fall back to a unit gap if the port is perpendicular to `ê`
        // (degenerate extent) so `width = area / length` stays finite.
        let length = (hi - lo).max(f64::EPSILON);
        TransmonPort {
            faces,
            e_hat,
            width: area / length,
            length,
        }
    }

    /// Readout port 1 ([`PHYS_PORT_1`], direction [`PORT_E_HAT`] = +X).
    pub fn port_1(&self) -> TransmonPort {
        self.port_from_tag(PHYS_PORT_1, PORT_E_HAT)
    }

    /// Readout port 2 ([`PHYS_PORT_2`], direction [`PORT_E_HAT`] = +X).
    pub fn port_2(&self) -> TransmonPort {
        self.port_from_tag(PHYS_PORT_2, PORT_E_HAT)
    }

    /// Junction lumped-element port ([`PHYS_LUMPED_ELEMENT`], direction
    /// [`JUNCTION_E_HAT`] = +Y). The BC is Phase B's job; this returns the
    /// tagged surface + direction only.
    pub fn lumped_element_port(&self) -> TransmonPort {
        self.port_from_tag(PHYS_LUMPED_ELEMENT, JUNCTION_E_HAT)
    }
}

/// Lumped-port geometry recovered from a transmon port tag: owned face
/// list plus the uniform-port parameters (mirrors
/// [`super::SpiralPort`]).
#[derive(Clone, Debug)]
pub struct TransmonPort {
    /// Port faces (0-based node triples into the fixture mesh).
    pub faces: Vec<[u32; 3]>,
    /// Unit field direction `ê`.
    pub e_hat: [f64; 3],
    /// Port width `w` (extent perpendicular to `ê`), from the tagged
    /// triangle area.
    pub width: f64,
    /// Gap length `l` (extent along `ê`).
    pub length: f64,
}

impl TransmonPort {
    /// Palace-style uniform [`LumpedPort`] on these faces with lumped
    /// resistance `R` (units of η₀) and incident drive voltage `V_inc`
    /// across the gap.
    pub fn lumped_port(&self, resistance: f64, v_inc: c64) -> LumpedPort<'_> {
        LumpedPort {
            faces: &self.faces,
            e_hat: self.e_hat,
            resistance,
            width: self.width,
            length: self.length,
            v_inc,
        }
    }
}

/// Load the bundled coarse transmon **smoke** fixture
/// (`transmon_smoke.msh`) — currently a schema-faithful PLACEHOLDER (see
/// module docs). Same physical-group convention as the real DeviceLayout
/// fixture, so callers are unchanged when the real mesh is swapped in.
pub fn read_transmon_smoke_fixture() -> Result<TransmonFixture, MeshError> {
    read_transmon_fixture_from_bytes(TRANSMON_SMOKE_MSH)
}

/// Load a transmon fixture from arbitrary MSH 4.1 ASCII bytes following
/// the same physical-group convention as the bundled mesh (see module
/// docs) — e.g. the real DeviceLayout mesh generated by
/// `reference/julia/generate_transmon_fixture.jl`.
///
/// Reuses the shared surface-tag scanners (`parse_entities_physical_tags`
/// / `parse_elements_with_entity_tags` in [`super::msh_tags`]) — the base
/// [`GmshReader`] drops triangle blocks, so without these the
/// metal/port/junction/boundary surface tags would be lost.
pub fn read_transmon_fixture_from_bytes(source: &[u8]) -> Result<TransmonFixture, MeshError> {
    let mesh = GmshReader.read_tet_mesh(source)?;

    let text = std::str::from_utf8(source)
        .map_err(|e| MeshError::Parse(format!("fixture is not UTF-8: {e}")))?;

    let entity_phys = parse_entities_physical_tags(text)?;
    let (tet_physical_tags, boundary_triangles, triangle_physical_tags) =
        parse_elements_with_entity_tags(text, &mesh, &entity_phys)?;

    Ok(TransmonFixture {
        mesh,
        tet_physical_tags,
        boundary_triangles,
        triangle_physical_tags,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sapphire_eps_lab_is_rotated_symmetric() {
        let lab = sapphire_eps_lab();
        // Symmetric (R·diag·Rᵀ is always symmetric).
        assert!((lab[0][1] - lab[1][0]).abs() < 1e-12);
        assert!((lab[0][2] - lab[2][0]).abs() < 1e-12);
        assert!((lab[1][2] - lab[2][1]).abs() < 1e-12);
        // z is the rotation axis → zz unchanged, xz/yz zero.
        assert!((lab[2][2] - 11.5).abs() < 1e-12);
        assert!(lab[0][2].abs() < 1e-12);
        assert!(lab[1][2].abs() < 1e-12);
        // The in-plane block is isotropic (ε₁ = ε₂ = 9.3), so the
        // rotation leaves it diagonal: xx = yy = 9.3, xy = 0. This is the
        // known degenerate case — the off-diagonal coupling only appears
        // when ε₁ ≠ ε₂ (sapphire's optic axis tilted out of plane). We
        // pin the exact values so a future ε-diag change is visible.
        assert!((lab[0][0] - 9.3).abs() < 1e-12);
        assert!((lab[1][1] - 9.3).abs() < 1e-12);
        assert!(lab[0][1].abs() < 1e-12);
        // Trace is rotation-invariant.
        let trace = lab[0][0] + lab[1][1] + lab[2][2];
        assert!((trace - (9.3 + 9.3 + 11.5)).abs() < 1e-12);
    }

    #[test]
    fn sapphire_eps_scalar_is_trace_average() {
        assert!((sapphire_eps_scalar() - (9.3 + 9.3 + 11.5) / 3.0).abs() < 1e-12);
    }
}
