//! Electrostatic capacitance-extraction benchmark generator (Epic #475,
//! issue #478): solve the coax and concentric-sphere oracles + the
//! two-sphere-in-grounded-box off-diagonal case, extract the Maxwell
//! capacitance matrices, and emit the committed benchmark fixture
//! `benchmarks/electrostatic/results.toml`.
//!
//! Run with:
//!
//! ```text
//!   cargo run -p geode-core --example electrostatic_capacitance --release
//! ```
//!
//! Emits `benchmarks/electrostatic/results.toml` — the baseline the
//! `tests/electrostatic_capacitance.rs` oracles guard, plus the pending
//! Palace `terminal-C` cross-check slot (`status = "pending_operator_run"`,
//! same toolchain-gap convention as the patch-antenna and spiral-inductor
//! benchmarks). Override the output root with `$ELECTROSTATIC_BENCH_DIR`.

use std::f64::consts::PI;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use geode_core::assembly::electrostatic::{
    ConductorSurface, EPS_0, Electrode, assemble_electrostatic, extract_capacitance,
};
use geode_core::mesh::electrostatic_fixtures::{
    coax_shell_mesh, sphere_shell_mesh, two_sphere_box_mesh,
};

fn main() {
    // ---- Oracle 1: coaxial cylinder ----
    let (coax_a, coax_b, coax_len) = (1.0, 2.5, 1.0);
    let coax_fx = coax_shell_mesh(coax_a, coax_b, coax_len, 128, 8, 1);
    let coax_eps = vec![1.0; coax_fx.mesh.n_tets()];
    let coax_rho = vec![0.0; coax_fx.mesh.n_tets()];
    let coax_inner = Electrode {
        name: "inner".into(),
        nodes: coax_fx.inner.clone(),
        voltage: 1.0,
    };
    let coax_conductors = [coax_inner];
    let coax_sys = assemble_electrostatic(
        &coax_fx.mesh,
        &coax_eps,
        &coax_rho,
        &coax_conductors,
        &coax_fx.outer,
    )
    .unwrap();
    let coax_surf = vec![ConductorSurface {
        triangles: coax_fx.inner_triangles.clone(),
    }];
    let coax_cm = extract_capacitance(
        &coax_sys,
        &coax_fx.mesh,
        &coax_eps,
        &coax_conductors,
        &coax_fx.outer,
        &coax_surf,
    )
    .unwrap();
    let coax_c_per_l = coax_cm.c[0][0] / coax_len;
    let coax_flux_per_l = coax_cm.c_flux_diag[0].unwrap() / coax_len;
    let coax_exact = 2.0 * PI * EPS_0 / (coax_b / coax_a).ln();
    let coax_rel = (coax_c_per_l - coax_exact).abs() / coax_exact;
    let coax_flux_rel = (coax_flux_per_l - coax_exact).abs() / coax_exact;

    // ---- Oracle 2: concentric spheres (fine + convergence pair) ----
    let (sph_a, sph_b) = (1.0, 2.0);
    let sph_exact = 4.0 * PI * EPS_0 * sph_a * sph_b / (sph_b - sph_a);
    let (c_coarse, _, _) = sphere_cap(sph_a, sph_b, 4, 3);
    let (c_fine, flux_fine, sph_nodes) = sphere_cap(sph_a, sph_b, 4, 6);
    let rel_coarse = (c_coarse - sph_exact).abs() / sph_exact;
    let rel_fine = (c_fine - sph_exact).abs() / sph_exact;
    let sph_order = (rel_coarse / rel_fine).log2();
    let sph_flux_rel = (flux_fine - sph_exact).abs() / sph_exact;

    // ---- Oracle 3: two spheres in a grounded box ----
    let (ts_r, ts_sep, ts_half) = (0.5, 2.0, 5.0);
    let ts_fx = two_sphere_box_mesh(ts_r, ts_sep, ts_half, 40);
    let ts_eps = vec![1.0; ts_fx.mesh.n_tets()];
    let ts_rho = vec![0.0; ts_fx.mesh.n_tets()];
    let cond_a = Electrode {
        name: "A".into(),
        nodes: ts_fx.sphere_a.clone(),
        voltage: 1.0,
    };
    let cond_b = Electrode {
        name: "B".into(),
        nodes: ts_fx.sphere_b.clone(),
        voltage: 0.0,
    };
    let conds = vec![cond_a, cond_b];
    let ts_sys =
        assemble_electrostatic(&ts_fx.mesh, &ts_eps, &ts_rho, &conds, &ts_fx.ground).unwrap();
    let ts_cm =
        extract_capacitance(&ts_sys, &ts_fx.mesh, &ts_eps, &conds, &ts_fx.ground, &[]).unwrap();
    let ts_asym = ts_cm.max_rel_asymmetry();
    let c_mutual = ts_cm.c[0][1].abs();
    let c_image = 4.0 * PI * EPS_0 * ts_r * ts_r / ts_sep;
    let ts_rel = (c_mutual - c_image).abs() / c_image;

    // ---- Emit results.toml ----
    let mut t = String::with_capacity(4096);
    t.push_str("# Auto-generated by `cargo run -p geode-core --release \\\n");
    t.push_str("#   --example electrostatic_capacitance`.\n");
    t.push_str("# Do NOT edit by hand — regenerate after any intentional change.\n");
    t.push_str("# Consumed by `tests/electrostatic_capacitance.rs`.\n\n");

    t.push_str("[meta]\n");
    let _ = writeln!(
        t,
        "description = \"Electrostatic solver + Maxwell capacitance-matrix extraction (Epic #475, Palace Electrostatic parity): 3-D P1 tet scalar solve of -div(eps grad phi)=rho with per-element eps_r and multi-conductor Dirichlet electrodes; N unit-voltage solves -> C_ij = phi_i^T K phi_j (full K). Programmatically-meshed coax + concentric-sphere oracles at <=1%, two-sphere off-diagonal at an honest box-truncation band.\""
    );
    t.push_str("method = \"energy_reaction\"  # C_ij = phi_i^T K phi_j, full unconstrained K\n");
    t.push_str("cross_check = \"surface_flux\"  # Q = closed-surface integral of eps*(-grad phi).n, looser band\n");
    t.push_str("element = \"p1_tet\"\n");
    t.push_str("permittivity_f_per_m = 8.8541878128e-12  # eps_0\n\n");

    t.push_str("[oracles.coax]\n");
    t.push_str("# C/L = 2*pi*eps_0*eps_r / ln(b/a)\n");
    let _ = writeln!(t, "inner_radius_a = {coax_a}");
    let _ = writeln!(t, "outer_radius_b = {coax_b}");
    let _ = writeln!(t, "eps_r = 1.0");
    let _ = writeln!(t, "nodes = {}", coax_fx.mesh.n_nodes());
    let _ = writeln!(t, "tets = {}", coax_fx.mesh.n_tets());
    let _ = writeln!(t, "c_per_length_fem = {coax_c_per_l:.9e}");
    let _ = writeln!(t, "c_per_length_exact = {coax_exact:.9e}");
    let _ = writeln!(t, "rel_err = {coax_rel:.6e}  # bar: <= 1e-2");
    let _ = writeln!(t, "c_per_length_flux = {coax_flux_per_l:.9e}");
    let _ = writeln!(
        t,
        "flux_rel_err = {coax_flux_rel:.6e}  # looser sanity band (~8%), not the bar\n"
    );

    t.push_str("[oracles.concentric_spheres]\n");
    t.push_str("# C = 4*pi*eps_0*eps_r * a*b/(b-a)\n");
    let _ = writeln!(t, "inner_radius_a = {sph_a}");
    let _ = writeln!(t, "outer_radius_b = {sph_b}");
    let _ = writeln!(t, "eps_r = 1.0");
    let _ = writeln!(t, "nodes = {sph_nodes}");
    let _ = writeln!(t, "c_fem = {c_fine:.9e}");
    let _ = writeln!(t, "c_exact = {sph_exact:.9e}");
    let _ = writeln!(t, "rel_err = {rel_fine:.6e}  # bar: <= 1e-2");
    let _ = writeln!(
        t,
        "rel_err_coarse = {rel_coarse:.6e}  # n_r = 3 (vs fine n_r = 6)"
    );
    let _ = writeln!(
        t,
        "convergence_order = {sph_order:.4}  # ~2 => O(h^2) P1 energy"
    );
    let _ = writeln!(t, "c_flux = {:.9e}", flux_fine);
    let _ = writeln!(
        t,
        "flux_rel_err = {sph_flux_rel:.6e}  # wide sanity band (~15%), not the bar\n"
    );

    t.push_str("[oracles.two_sphere_box]\n");
    t.push_str("# Two conductor spheres in a grounded box; off-diagonal Maxwell term.\n");
    t.push_str("# Reference: leading image-charge term |C_12| ~ 4*pi*eps_0*r^2/sep, with\n");
    t.push_str("# higher-order images + finite-box truncation + staircase-sphere\n");
    t.push_str("# discretization setting an HONEST wide band (not 1%).\n");
    let _ = writeln!(t, "sphere_radius = {ts_r}");
    let _ = writeln!(t, "separation = {ts_sep}");
    let _ = writeln!(t, "box_half_side = {ts_half}");
    let _ = writeln!(t, "nodes = {}", ts_fx.mesh.n_nodes());
    let _ = writeln!(t, "c_aa = {:.9e}", ts_cm.c[0][0]);
    let _ = writeln!(t, "c_ab = {:.9e}", ts_cm.c[0][1]);
    let _ = writeln!(t, "c_ba = {:.9e}", ts_cm.c[1][0]);
    let _ = writeln!(t, "c_bb = {:.9e}", ts_cm.c[1][1]);
    let _ = writeln!(t, "max_rel_asymmetry = {ts_asym:.3e}  # hard check: < 1e-9");
    let _ = writeln!(t, "c_mutual_abs = {c_mutual:.9e}");
    let _ = writeln!(t, "c_mutual_image_leading = {c_image:.9e}");
    let _ = writeln!(
        t,
        "mutual_rel_err_vs_image = {ts_rel:.6e}  # honest band, box-truncation-dominated\n"
    );

    // Pending Palace terminal-C cross-check slot.
    t.push_str("[oracles.palace]\n");
    t.push_str("status = \"pending_operator_run\"\n");
    t.push_str(
        "note = \"Palace's Electrostatic module extracts the same terminal capacitance matrix (terminal-C.csv). Palace is not installed on the generation machine (Docker build recipe only, per #476's verified note), so this slot stays pending until an operator runs Palace. PalaceResults currently parses s-parameters.csv; populating this slot needs either a small terminal-C.csv ingester extension or a manually-populated block carrying palace_version + config_sha256 provenance. Same toolchain-gap convention as the FastHenry slot of benchmarks/spiral_inductor/results.toml and the Palace slot of benchmarks/patch_antenna/results.toml. Tolerance band when populated: 1% on the coax/sphere diagonal C, honest few-% on the two-sphere off-diagonal.\"\n",
    );

    let bench_dir = std::env::var("ELECTROSTATIC_BENCH_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../benchmarks/electrostatic")
        });
    fs::create_dir_all(&bench_dir).expect("create benchmark dir");
    let path = bench_dir.join("results.toml");
    fs::write(&path, &t).expect("write benchmark TOML");

    eprintln!("wrote {}", path.display());
    eprintln!(
        "coax C/L rel = {:.4}%; spheres C rel = {:.4}% (order {sph_order:.2}); \
         two-sphere |C_12| rel-vs-image = {:.1}%, asym = {ts_asym:.1e}",
        coax_rel * 100.0,
        rel_fine * 100.0,
        ts_rel * 100.0
    );
}

/// Concentric-sphere capacitance at a given resolution: returns
/// `(C, surface-flux C, node count)`.
fn sphere_cap(a: f64, b: f64, subdiv: usize, n_r: usize) -> (f64, f64, usize) {
    let fx = sphere_shell_mesh(a, b, subdiv, n_r);
    let eps_r = vec![1.0; fx.mesh.n_tets()];
    let rho = vec![0.0; fx.mesh.n_tets()];
    let inner = Electrode {
        name: "inner".into(),
        nodes: fx.inner.clone(),
        voltage: 1.0,
    };
    let conductors = [inner];
    let sys = assemble_electrostatic(&fx.mesh, &eps_r, &rho, &conductors, &fx.outer).unwrap();
    let surf = vec![ConductorSurface {
        triangles: fx.inner_triangles.clone(),
    }];
    let cm = extract_capacitance(&sys, &fx.mesh, &eps_r, &conductors, &fx.outer, &surf).unwrap();
    (cm.c[0][0], cm.c_flux_diag[0].unwrap(), fx.mesh.n_nodes())
}
