//! Regenerate the convergence regression fixture
//! `crates/geode-core/tests/fixtures/cube_convergence.toml`.
//!
//! The fixture captures the per-level ground-mode eigenvalues that this
//! build produces for the Dirichlet Laplacian on the unit cube. The numbers
//! are baselines — what the assembly + faer eigensolver produces today —
//! not analytic targets. Their job is to catch unintended regressions in
//! assembly or eigensolver semantics.
//!
//! Run with:
//!
//! ```sh
//! cargo run -p geode-core --release --example regen_cube_convergence_fixture
//! ```
//!
//! `--release` is required because faer 0.24's `gevd::qz_real` performs
//! subtractions that wrap under `debug-assertions`, producing
//! `attempt to subtract with overflow` panics even though the release math
//! is correct. The same constraint applies to the regression test that
//! consumes this fixture (see `tests/cube_convergence_regression.rs`).
//!
//! This binary is **not** run from CI. Regenerate manually when an
//! intentional change alters the produced values; commit the updated
//! TOML and call out the reason in the PR.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use burn::tensor::backend::BackendTypes;
use geode_core::assembly::p1::{assemble_global_p1, upload_mesh};
use geode_core::backend::DefaultBackend;
use geode_core::eigen::dense::{
    EigenSolver, FaerDenseEigensolver, apply_dirichlet_bc, burn_matrix_to_faer, cube_interior_mask,
};
use geode_core::mesh::cube_tet_mesh;

type B = DefaultBackend;

/// Mesh refinements covered by the fixture. Mirrors
/// `examples/eigen_convergence.rs` so the human-readable sweep and the
/// regression baseline stay in lockstep.
const LEVELS: &[usize] = &[3, 4, 5, 6, 8, 10, 12];

fn ground_mode(n: usize) -> f64 {
    let device = <B as BackendTypes>::Device::default();
    let mesh = cube_tet_mesh(n, 1.0);
    let (nodes, tets) = upload_mesh::<B>(&mesh, &device);
    let sys = assemble_global_p1(nodes, tets, mesh.n_nodes());
    let k = burn_matrix_to_faer(sys.k);
    let m = burn_matrix_to_faer(sys.m);
    let mask = cube_interior_mask(&mesh.nodes, 1.0);
    let (k_int, m_int) = apply_dirichlet_bc(k.as_ref(), m.as_ref(), &mask).expect("BC reduction");
    FaerDenseEigensolver
        .smallest_eigenvalues(k_int.as_ref(), m_int.as_ref(), 1)
        .expect("eigensolve")[0]
}

fn current_commit() -> String {
    Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
            } else {
                None
            }
        })
        .unwrap_or_else(|| "unknown".to_string())
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("cube_convergence.toml")
}

fn main() {
    let analytic = 3.0 * std::f64::consts::PI.powi(2);

    let mut rows: Vec<(usize, f64)> = Vec::with_capacity(LEVELS.len());
    for &n in LEVELS {
        let lam = ground_mode(n);
        eprintln!(
            "n = {n:>2}  λ_h = {lam:.12e}  rel_err = {:.6e}",
            (lam - analytic).abs() / analytic
        );
        rows.push((n, lam));
    }

    let commit = current_commit();
    let mut out = String::new();
    out.push_str("# Auto-generated by `cargo run -p geode-core --release \\\n");
    out.push_str("#   --example regen_cube_convergence_fixture`.\n");
    out.push_str("# Do NOT edit by hand — regenerate after any intentional change\n");
    out.push_str("# to assembly or the eigensolver, then commit the new values.\n");
    out.push_str("#\n");
    out.push_str("# Consumed by `tests/cube_convergence_regression.rs`.\n");
    out.push('\n');
    out.push_str("[meta]\n");
    out.push_str(
        "description = \"Ground-mode eigenvalue of unit cube Dirichlet Laplacian via P1 FEM.\"\n",
    );
    out.push_str(&format!("analytic = {analytic:.15e}  # 3π²\n"));
    out.push_str(&format!("generated_at_commit = \"{commit}\"\n"));
    out.push_str("# Levels mirror `examples/eigen_convergence.rs`.\n");
    out.push_str(&format!("levels = {:?}\n", LEVELS));
    out.push('\n');

    for (n, lam) in &rows {
        let rel_err = (lam - analytic).abs() / analytic;
        out.push_str(&format!("[n_{n}]\n"));
        out.push_str(&format!("eigenvalue = {lam:.15e}\n"));
        out.push_str(&format!("rel_err = {rel_err:.15e}\n"));
        out.push('\n');
    }

    let path = fixture_path();
    fs::create_dir_all(path.parent().expect("fixture parent dir")).expect("create fixtures dir");
    fs::write(&path, out).expect("write fixture");
    eprintln!("\nWrote fixture: {}", path.display());
}
