"""Tests for ``anvil.skills.deck.lib.auto_shrink_detector`` (issue #102 / #100b).

The detector is the deterministic companion to ``deck-vision``'s qualitative
``v1 vertical_overflow`` — it catches Marp's silent CSS auto-shrink that
neither ``marp_lint`` (source-side) nor ``deck-vision`` (one API call per
slide) catches on its own.

These tests exercise the detector against synthetic Pillow-drawn PNGs
generated by ``fixtures/auto_shrink/conftest.py``. Synthetic-only is the
documented coverage scope (per the maintainer resolution on #102) — the
four canary decks stay in studio as a manual post-merge sanity check.

Fixtures (built at test-time, NOT committed as binary):

- **F1** — three healthy peer slides. No findings.
- **F2** — two healthy peer slides + one auto-shrunk outlier. Slide 3
  must be flagged with ``rule="auto-shrink-fit-compression"``.
- **F3** — one ``title``-class singleton (zero peers). MUST NOT flag;
  must record the class as skipped with a reason.
- **F4** — three equally-light peers. Ratio 1.0; no findings.
- **F5** — peers at bm 7/9/11% (median 9%), candidate at bm 13.5% — the
  ratio condition (1.5x) is matched but the absolute floor (>18%) is
  NOT. Asserts both conditions are required, not OR-of-conditions.
- **F6** — pure classification test against the committed ``deck.md``
  fixture. Asserts ``_classify_slides`` returns the expected per-slide
  class list (mix of ``title``, ``content``, ``ask``).

Deck-distinct filename per the #58 packaging convention.

Runs under either ``python -m unittest discover anvil/skills/deck/tests/``
or ``pytest anvil/skills/deck/tests/``.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Gate the entire module on the ``[auto_shrink]`` optional extra. The
# detector under test, the fixture-generation conftest, and the
# ``_content_bbox`` pixel primitive all need ``Pillow`` and ``numpy`` at
# test time (the fixtures' ``_make_png`` paints synthetic PNGs with
# Pillow, and the detector's argmax reduction is numpy-based). When the
# extra is absent (stock venv without ``uv pip install -e .[auto_shrink]``)
# pytest skips the whole file with a clear reason instead of erroring at
# collection or first fixture call. Matches the precedent set by
# ``tests/lib/test_figures.py`` for matplotlib. See pyproject.toml's top
# comment for the convention.
pytest.importorskip("PIL", reason="Pillow not installed ([auto_shrink] extra)")
pytest.importorskip("numpy", reason="numpy not installed ([auto_shrink] extra)")


# Ensure repo root is importable. This file lives at
# anvil/skills/deck/tests/test_auto_shrink_detector.py — four levels deep
# from the repo root.
_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parents[3]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Make the deck-local lib dir importable so the test reaches the detector
# without forcing a package install. Matches the convention used by
# ``test_marp_lint.py``.
_LIB = _HERE.parent / "lib"
if str(_LIB) not in sys.path:
    sys.path.insert(0, str(_LIB))

from auto_shrink_detector import (  # noqa: E402
    AutoShrinkFinding,
    AutoShrinkResult,
    Thresholds,
    _classify_slides,
    _content_bbox,
    detect_auto_shrink,
)


# --- F1 --------------------------------------------------------------------


class TestF1_HealthyDeck:
    """F1 — three peers all at ~90% fill. Detector must produce zero findings."""

    def test_no_findings(self, auto_shrink_fixture_root: Path) -> None:
        case = auto_shrink_fixture_root / "F1"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert isinstance(result, AutoShrinkResult)
        assert not result.skipped
        assert result.findings == []

    def test_per_class_median_computed(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F1"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        # Three peers, all in the ``content`` class, all with bm ~10%.
        # The class must have a baseline median entry.
        assert "content" in result.per_class_medians
        median = result.per_class_medians["content"]
        # Detector measures the rendered PNG — synthetic fills aren't
        # pixel-exact (40-px padding above the rect changes the bbox
        # slightly). Just sanity-check the order of magnitude.
        assert 0.0 <= median <= 0.20


# --- F2 --------------------------------------------------------------------


class TestF2_AutoShrunkOutlier:
    """F2 — slide 3 is the outlier (~60% bottom margin vs peers' ~15%)."""

    def test_slide_3_flagged(self, auto_shrink_fixture_root: Path) -> None:
        case = auto_shrink_fixture_root / "F2"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert not result.skipped
        assert len(result.findings) == 1, (
            f"expected exactly 1 finding, got {len(result.findings)}: "
            f"{[f.to_dict() for f in result.findings]}"
        )
        f = result.findings[0]
        assert isinstance(f, AutoShrinkFinding)
        assert f.slide == 3
        assert f.class_name == "content"
        assert f.severity == "error"
        assert f.rule == "auto-shrink-fit-compression"
        # The flagged slide MUST exceed both the ratio threshold and the
        # absolute floor.
        assert f.ratio > 1.5
        assert f.bottom_margin_norm > 0.18

    def test_message_is_actionable(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F2"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        message = result.findings[0].message
        # The message must surface the slide number and a fix hint so the
        # reviser knows what to do.
        assert "Slide 3" in message
        assert "auto-shrink" in message.lower() or "fit-to-frame" in message.lower()

    def test_to_dict_round_trip(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F2"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        summary = result.to_dict()
        # The summary shape must declare the lint ran, must have an
        # error count of 1, and must include the finding's dict form.
        assert summary["ran"] is True
        assert summary["errors"] == 1
        assert summary["findings"][0]["slide"] == 3
        assert summary["findings"][0]["rule"] == "auto-shrink-fit-compression"


# --- F3 --------------------------------------------------------------------


class TestF3_SingletonClassNeverFlagged:
    """F3 — one ``title`` slide, deliberately deeply-shrunk.

    The singleton-class skip rule must win over the absolute-floor rule
    — a slide with no peers cannot be an outlier-vs-peers regardless of
    its individual margins. This is the design contract (curator D4):
    "The detector should NEVER flag a singleton-class slide; auto-shrink
    against itself is a tautology."
    """

    def test_no_findings(self, auto_shrink_fixture_root: Path) -> None:
        case = auto_shrink_fixture_root / "F3"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert not result.skipped
        assert result.findings == []

    def test_singleton_class_recorded_in_skipped(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F3"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        # The skipped-class channel must surface the reason so a future
        # user reading ``_summary.md`` knows WHY this class wasn't
        # checked.
        assert "title" in result.skipped_classes
        reason = result.skipped_classes["title"]
        assert "1 page" in reason or "1 page(s)" in reason
        assert "minimum 3" in reason


# --- F4 --------------------------------------------------------------------


class TestF4_RatioOneNotFlagged:
    """F4 — three equally-light peers. Ratio = 1.0; no findings.

    Asserts the rule is "outlier vs peer", not "absolute floor by
    itself". Even though all three slides have ~50% bottom margin
    (well above the 18% absolute floor), none should flag because none
    is an outlier vs. its peers.
    """

    def test_no_findings(self, auto_shrink_fixture_root: Path) -> None:
        case = auto_shrink_fixture_root / "F4"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert not result.skipped
        assert result.findings == [], (
            "F4 must produce zero findings — the rule requires the "
            "OUTLIER vs peer condition; absolute-floor alone is "
            "insufficient. Got: "
            f"{[f.to_dict() for f in result.findings]}"
        )


# --- F5 --------------------------------------------------------------------


class TestF5_AbsoluteFloorRequired:
    """F5 — candidate exceeds the ratio threshold but not the absolute floor.

    Peers at bm 7%, 9%, 11% (median 9%); candidate at bm 13.5%
    (= 1.5x median, AT the ratio boundary, but 13.5% < 18% absolute
    floor). Asserts both conditions are required — a deck whose peer
    slides ALL have small bottom margins should not start flagging
    candidates whose only sin is being slightly worse than that already-
    tight baseline.
    """

    def test_no_findings(self, auto_shrink_fixture_root: Path) -> None:
        case = auto_shrink_fixture_root / "F5"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert not result.skipped
        assert result.findings == [], (
            "F5 must produce zero findings — the candidate is at the "
            "ratio threshold but below the absolute floor; both "
            "conditions are required. Got: "
            f"{[f.to_dict() for f in result.findings]}"
        )


# --- F6 — classification ----------------------------------------------------


class TestF6_Classification:
    """F6 — ``_classify_slides`` returns the right per-slide class list."""

    def test_no_directives_default_to_content(self) -> None:
        source = """---
marp: true
---

# Slide 1

Body.

---

## Slide 2

Body.
"""
        classes = _classify_slides(source)
        assert classes == ["content", "content"]

    def test_title_and_ask_directives_recognised(self) -> None:
        source = """---
marp: true
---

<!-- _class: title -->

# Title

---

## Content

---

<!-- _class: ask -->

# Ask
"""
        classes = _classify_slides(source)
        assert classes == ["title", "content", "ask"]

    def test_committed_deck_md_fixture_classifies_correctly(self) -> None:
        # The committed deck.md fixture mixes title + 3 content + ask.
        # This is the F6 case proper — a real on-disk fixture, not an
        # in-memory string.
        fixture = (
            _HERE
            / "fixtures"
            / "auto_shrink"
            / "deck.md"
        )
        assert fixture.exists(), "F6 fixture deck.md must exist"
        classes = _classify_slides(fixture.read_text(encoding="utf-8"))
        assert classes == [
            "title",
            "content",
            "content",
            "content",
            "ask",
        ]

    def test_yaml_frontmatter_class_is_not_a_per_slide_directive(self) -> None:
        # A ``class:`` field inside the leading YAML frontmatter is the
        # deck-wide default; it must NOT cause every slide to be
        # classified as that class. (Marp's per-slide override is only
        # the ``<!-- _class: ... -->`` HTML comment form.)
        source = """---
marp: true
class: lead
---

# Slide 1

---

# Slide 2
"""
        classes = _classify_slides(source)
        assert classes == ["content", "content"]


# --- skip-paths and edge cases ---------------------------------------------


class TestSkipPaths:
    """Verify graceful-skip when inputs are missing or deps unavailable."""

    def test_missing_pdf_returns_skipped_result(
        self, tmp_path: Path
    ) -> None:
        # A missing deck.pdf must NOT raise — the detector returns a
        # skipped result that the deck-review command can surface as
        # an info-level lint note.
        deck_md = tmp_path / "deck.md"
        deck_md.write_text("# Slide 1\n", encoding="utf-8")
        result = detect_auto_shrink(
            deck_pdf=tmp_path / "does-not-exist.pdf",
            deck_md=deck_md,
        )
        assert result.skipped
        assert result.reason is not None
        assert "not found" in result.reason

    def test_missing_md_returns_skipped_result(
        self, tmp_path: Path
    ) -> None:
        stub_pdf = tmp_path / "deck.pdf"
        stub_pdf.write_bytes(b"%PDF-stub\n")
        result = detect_auto_shrink(
            deck_pdf=stub_pdf,
            deck_md=tmp_path / "does-not-exist.md",
        )
        assert result.skipped
        assert result.reason is not None

    def test_missing_deps_returns_remediation(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Stub the preflight to simulate Pillow/numpy not installed.
        # The detector must return a skipped result carrying the
        # remediation message; it must NOT raise.
        from anvil.lib.render import AUTO_SHRINK_REMEDIATION
        import anvil.lib.render as render_module

        monkeypatch.setattr(
            render_module,
            "check_auto_shrink_deps_available",
            lambda: False,
        )

        deck_md = tmp_path / "deck.md"
        deck_md.write_text("# Slide 1\n", encoding="utf-8")
        stub_pdf = tmp_path / "deck.pdf"
        stub_pdf.write_bytes(b"%PDF-stub\n")
        result = detect_auto_shrink(
            deck_pdf=stub_pdf,
            deck_md=deck_md,
        )
        assert result.skipped
        assert result.reason == AUTO_SHRINK_REMEDIATION


class TestThresholdsOverride:
    """A consumer with a custom theme can override the thresholds dataclass."""

    def test_override_floor_eliminates_finding(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F2 normally flags slide 3. Raise the absolute floor above 60%
        # and the finding disappears — proves the threshold is honoured.
        case = auto_shrink_fixture_root / "F2"
        custom = Thresholds(abs_bottom_margin_floor=0.99)
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
            thresholds=custom,
        )
        assert result.findings == []

    def test_override_ratio_threshold_changes_outcome(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F1 (healthy peers) — lowering the ratio threshold to 1.01
        # would normally start flagging any peer-set outlier, but here
        # all three peers are clustered near each other so even a tight
        # ratio shouldn't flag (median-vs-self is always 1.0 on a
        # 3-page deck where two are equidistant from the third).
        # Instead, lower the absolute floor so the only thing standing
        # between healthy-peer and flagged is the ratio threshold.
        case = auto_shrink_fixture_root / "F1"
        baseline_result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        # Baseline is zero findings.
        assert baseline_result.findings == []


class TestContentBboxPrimitive:
    """The pixel-level primitive measures bottom margin correctly.

    Direct test on ``_content_bbox`` independent of the per-class peer
    rule. Helps localise failures: if the detector's higher-level rule
    misfires, the bbox tests tell us whether the pixel layer is wrong
    or the per-class rule is wrong.
    """

    def test_full_height_content_has_zero_bottom_margin(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F2 slide 1 fills to 85%. Bottom margin should be near 15%.
        bbox = _content_bbox(
            auto_shrink_fixture_root / "F2" / "page-1.png",
            bg_tolerance=8,
            corner_margin_px=4,
            corner_patch_px=16,
        )
        assert bbox is not None
        # 1280 x 720 fixture. Content rect ends at y=int(720*0.85)=612.
        # Bottom margin in px = 720 - 612 - 1 = 107. Norm = 107/720 = ~0.149.
        # Allow ±2% slack for the int rounding the conftest applies.
        assert 0.13 <= bbox.bottom_margin_norm <= 0.17

    def test_auto_shrunk_content_has_large_bottom_margin(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F2 slide 3 fills to 40%. Bottom margin should be near 60%.
        bbox = _content_bbox(
            auto_shrink_fixture_root / "F2" / "page-3.png",
            bg_tolerance=8,
            corner_margin_px=4,
            corner_patch_px=16,
        )
        assert bbox is not None
        assert 0.58 <= bbox.bottom_margin_norm <= 0.62


# --- F6 / F7 — composite-rule regressions (issue #562) ---------------------


class TestF6_FitShrunkAllSignals:
    """F6 — fit-shrunk slide where all three signals fire.

    Issue #562 — the canary regression (GoodBoy slides 3/8). Marp's
    fit-to-scale shrink reduces top margin, bottom margin, AND content
    area together; the post-#562 composite rule must catch this even
    though the pre-#562 detector caught the same case via the
    bottom-margin signal alone. Regression guard: confirms the
    composite rule doesn't silently drop cases the legacy rule
    already caught.
    """

    def test_slide_4_flagged(self, auto_shrink_fixture_root: Path) -> None:
        case = auto_shrink_fixture_root / "F6"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert not result.skipped
        assert len(result.findings) == 1, (
            f"expected 1 finding for the fit-shrunk slide; got "
            f"{[f.to_dict() for f in result.findings]}"
        )
        f = result.findings[0]
        assert f.slide == 4
        assert f.class_name == "content"
        assert f.severity == "error"
        # Post-#562: the finding records which signals fired.
        # Expect at least two signals (composite quorum).
        assert len(f.signals_fired) >= 2

    def test_message_names_signals(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F6"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        msg = result.findings[0].message
        # Message must surface the slide number and identify the
        # composite signals that fired so the reviser knows why.
        assert "Slide 4" in msg
        # At least one signal phrase must be present in the message.
        has_phrase = any(
            phrase in msg
            for phrase in ("top-margin", "bottom-margin", "content-area")
        )
        assert has_phrase, f"expected signal phrase in message; got: {msg!r}"


class TestF6_TopAndContentOnly:
    """F6_TopAndContent — fit-shrunk slide where bottom-margin is SAFE.

    Issue #562 — the load-bearing composite-rule test. The candidate's
    bottom margin sits within 1.1x of the class median (so the
    bottom-margin-alone signal does NOT fire), but the top margin and
    content area both fire. Two-of-three quorum → flagged.

    This is exactly the failure mode the pre-#562 single-signal
    detector missed on the GoodBoy deck: slides 3/8 read as auto-shrunk
    to the VLM and to a human reviewer, but their bottom margins were
    close enough to peer median to slip past the bottom-margin-only
    rule. The composite rule MUST flag this case.
    """

    def test_slide_4_flagged_via_composite(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F6_TopAndContent"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert not result.skipped, (
            f"unexpected skip: reason={result.reason!r}"
        )
        assert len(result.findings) == 1, (
            f"expected 1 finding; got {[f.to_dict() for f in result.findings]}"
        )
        f = result.findings[0]
        assert f.slide == 4
        # At least two signals must have fired (composite quorum).
        assert len(f.signals_fired) >= 2
        # Top-margin and content-area should be among the firing
        # signals (the load-bearing pair for this fixture). Bottom-
        # margin MAY also fire because 16% bm / 15% peer median is
        # 1.07x and below the 1.5x ratio threshold — confirm by
        # checking the per-page measurements.
        assert "top_margin" in f.signals_fired
        assert "content_area" in f.signals_fired


class TestF7_SingleSignalNotFlagged:
    """F7 — only the content-area signal fires; composite quorum NOT met.

    Issue #562 — composite-rule false-positive guard. A page whose only
    distinguishing feature is a narrower bbox (single signal) must NOT
    flag under the two-of-three quorum. This is the F7 negative
    control: confirms the composite rule doesn't degenerate to "any
    single signal flags."
    """

    def test_no_findings_for_single_signal(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F7"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert not result.skipped
        assert result.findings == [], (
            f"F7 must produce zero findings — only content-area fires "
            f"and the composite quorum requires 2 of 3. Got: "
            f"{[f.to_dict() for f in result.findings]}"
        )


class TestExtendedMediansSurface:
    """Post-#562 ``per_class_medians_extended`` exposes all three signals."""

    def test_extended_medians_populated(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        case = auto_shrink_fixture_root / "F1"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        # F1 has three healthy peers in class "content". The extended
        # medians map must contain the triplet for the class.
        assert "content" in result.per_class_medians_extended
        trip = result.per_class_medians_extended["content"]
        assert set(trip.keys()) == {
            "bottom_margin",
            "top_margin",
            "content_area",
        }
        # Each value is in [0, 1] (a normalised fraction).
        for k, v in trip.items():
            assert 0.0 <= v <= 1.0, f"{k}={v} out of [0,1] range"

    def test_legacy_per_class_medians_still_populated(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # Backwards-compat: the legacy ``per_class_medians`` field
        # (bottom-margin only) must still be populated for readers
        # written against the pre-#562 API.
        case = auto_shrink_fixture_root / "F1"
        result = detect_auto_shrink(
            deck_pdf=case / "deck.pdf",
            deck_md=case / "deck.md",
            png_dir=case,
        )
        assert "content" in result.per_class_medians
        # Same value as the extended triplet's bottom_margin entry.
        assert result.per_class_medians["content"] == (
            result.per_class_medians_extended["content"]["bottom_margin"]
        )


class TestContentBboxNewProperties:
    """``ContentBbox`` exposes ``top_margin_norm`` and ``content_area_norm`` (#562)."""

    def test_top_margin_norm_computed(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F6 peer slide — content starts at top=5%; top_margin_norm
        # should be approximately 0.05.
        bbox = _content_bbox(
            auto_shrink_fixture_root / "F6" / "page-1.png",
            bg_tolerance=8,
            corner_margin_px=4,
            corner_patch_px=16,
        )
        assert bbox is not None
        assert 0.03 <= bbox.top_margin_norm <= 0.07

    def test_top_margin_norm_for_shrunk_slide(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F6 candidate — content starts at top=20%; top_margin_norm
        # should be approximately 0.20.
        bbox = _content_bbox(
            auto_shrink_fixture_root / "F6" / "page-4.png",
            bg_tolerance=8,
            corner_margin_px=4,
            corner_patch_px=16,
        )
        assert bbox is not None
        assert 0.18 <= bbox.top_margin_norm <= 0.22

    def test_content_area_norm_for_full_bbox(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F6 peer — bbox spans top=5% to bottom=85%, columns 5%-95%.
        # Area ≈ 0.80 × 0.90 = 0.72.
        bbox = _content_bbox(
            auto_shrink_fixture_root / "F6" / "page-1.png",
            bg_tolerance=8,
            corner_margin_px=4,
            corner_patch_px=16,
        )
        assert bbox is not None
        assert 0.68 <= bbox.content_area_norm <= 0.80

    def test_content_area_norm_for_shrunk_bbox(
        self, auto_shrink_fixture_root: Path
    ) -> None:
        # F6 candidate — bbox spans top=20% to bottom=68%, columns 18%-82%.
        # Area ≈ 0.48 × 0.64 = ~0.31.
        bbox = _content_bbox(
            auto_shrink_fixture_root / "F6" / "page-4.png",
            bg_tolerance=8,
            corner_margin_px=4,
            corner_patch_px=16,
        )
        assert bbox is not None
        assert 0.25 <= bbox.content_area_norm <= 0.35
