"""Generate `reference/fixtures/sphere_mie_small/tfjava_baseline.json`.

Phase J.5 / Issue #174 / Epic #88.

This script produces the schema-v1 ``tfjava_baseline.json`` fixture that the
Rust validation test ``crates/geode-validation/tests/sphere_mie_tfjava_reference.rs``
loads. It mirrors the TF-Java JVM + Python eigensolve seam exactly, following
the Phase H.4 precedent (``reference/tf_java/sphere_pml/gen_tfjava_baseline.py``):

1. Mesh I/O, edge enumeration, PEC mask, per-tet centroid vectors, and the
   diagonal anisotropic UPML tensor profile — all matches
   ``reference/numpy/sphere_mie.py``, which in turn mirrors
   ``reference/tf_java/sphere_mie/.../SphereMesh.java`` line-for-line. The
   TF-Java JVM path uses the same lexicographic edge ordering (TreeMap) as
   the NumPy reference (np.unique), so the assembled matrices are
   bit-equivalent modulo floating-point accumulation order.
2. Tensor-ε Nédélec assembly (real K + complex M) via the NumPy reference.
   The TF-Java JVM equivalent (ComplexNedelecAssemblyGraph) contracts the
   per-axis cofactor gram against the [nTets, 3] tensor placeholders inside
   the static graph and emits Re(M) and Im(M) as parallel f64 tensors via
   scatterNd; the NumPy COO->CSR scatter and the TF-Java scatterNd path
   produce identical numerical results to ~f64 ULP because both are batched
   per-element 6x6 scatters with identical input arithmetic. The Phase G.5
   sphere-PEC TF-Java vs NumPy comparison (PR #137) measured ~1.2e-5
   relative drift on the lowest eigenvalue on the 774-node mesh — the same
   accumulation-order effect, smaller on this 48-node mesh.
3. NO sign canonicalization (deliberate divergence from H.4): the
   anisotropic UPML pencil's physical eigenvalues carry Im(λ) < 0 on the
   small mesh — a property of the pencil, agreed on by LAPACK ZGGEV and
   faer QZ (see the J.2 fixture description). Sort by |Re(λ)| ascending
   (matches Burn's `FaerComplexEigensolver` and the J.2/J.4 baselines).
4. Same fixture schema as ``jax_baseline.json`` (PR #180) minus the
   JAX-specific autodiff-probe fields, for downstream comparator
   uniformity.

Why not Maven here?
===================
The fixture is generated by computing the numerical pipeline result; the
fact that TF-Java would produce the same result is verified by the
``tfjava-cube-cavity`` workflow's ``sphere-mie-tfjava`` job (added in
#174), which actually builds and runs the JVM end-to-end on CI and hard-
gates the live eigenvalues against both the NumPy J.2 baseline and this
checked-in fixture. This script is the maintainer convenience for local
regeneration and the source of truth for the checked-in fixture — exactly
the H.4 pattern.

CI policy
=========
The fixture is checked in. The CI workflow regenerates the live JVM
eigenresult on-demand and compares against the checked-in version (same
pattern as ``sphere_pml/tfjava_baseline.json``). If the JVM path drifts
beyond the documented Phase G.5 tolerance, the workflow fails and the
live eigenresult is uploaded as an artifact for the maintainer to inspect.

Usage
=====

    python3 reference/tf_java/sphere_mie/gen_tfjava_baseline.py
    python3 reference/tf_java/sphere_mie/gen_tfjava_baseline.py --sigma0 5.0
    python3 reference/tf_java/sphere_mie/gen_tfjava_baseline.py \\
        --out reference/fixtures/sphere_mie_small/tfjava_baseline.json
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent.parent
# Repo root on sys.path: `reference.*` resolves as PEP 420 namespace
# packages regardless of cwd (issue #187).
_REPO_ROOT_STR = str(Path(__file__).resolve().parents[3])
if _REPO_ROOT_STR not in sys.path:
    sys.path.insert(0, _REPO_ROOT_STR)

# Strict cross-IR window (#160 cluster closure): the TM_1,1 triplet.
STRICT_MODE_WINDOW_LEN = 3

# Burn-side acceptance constants mirrored from
# `crates/geode-core/tests/mie_sphere.rs` (and the J.2 generator).
TM11_REL_TOL = 0.08
Q_LOWER_BAND_TM11 = 1.5

# Tolerances applied to the on-disk baseline — same floors as the J.2 /
# J.4 sphere_mie_small fixtures.
EIG_C128_TOL_ABS = 5.0e-4
PHYSICAL_C128_TOL_ABS = 1.0e-4
Q_FACTOR_TOL_ABS = 5.0
RE_K_TOL_ABS = 1.0e-4
ANALYTIC_K_TOL_ABS = 1.0e-9
SIGMA_ZERO_RE_TOL_ABS = 5.0e-5


def _git_commit() -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=REPO_ROOT,
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _numpy_baseline_path() -> Path:
    return REPO_ROOT / "reference" / "fixtures" / "sphere_mie_small" / "baseline.json"


def _default_out_path() -> Path:
    return REPO_ROOT / "reference" / "fixtures" / "sphere_mie_small" / "tfjava_baseline.json"


def _default_mesh_path() -> Path:
    # Shared with the #158 sphere_pml_small fixture — not duplicated.
    return REPO_ROOT / "reference" / "fixtures" / "sphere_pml_small" / "sphere.msh"


def _interleave_c128(z: np.ndarray) -> list[float]:
    """Real-imag interleaved encoding (row-major flattened) per
    `reference/SCHEMA.md` "Complex encoding (c128)"."""
    z = np.ascontiguousarray(z, dtype=np.complex128).reshape(-1)
    return z.view(np.float64).tolist()


def main():
    parser = argparse.ArgumentParser(
        description="Generate TF-Java sphere-Mie (tensor-ε UPML) reference fixture"
    )
    parser.add_argument(
        "--out", default=str(_default_out_path()),
        help="Output JSON path",
    )
    parser.add_argument(
        "--mesh", default=str(_default_mesh_path()),
        help="Path to the small sphere.msh",
    )
    parser.add_argument(
        "--sigma0", type=float, default=5.0,
        help="UPML absorption strength (default 5.0)",
    )
    parser.add_argument(
        "--n-index", type=float, default=1.5,
        help="Dielectric refractive index (default 1.5)",
    )
    parser.add_argument(
        "--k0-ref", type=float, default=2.0,
        help="Reference wavenumber ω heuristic (default 2.0)",
    )
    parser.add_argument(
        "--n-take", type=int, default=5,
        help="Number of physical eigenvalues to retain (default 5)",
    )
    parser.add_argument(
        "--tol", type=float, default=1.0e-4,
        help="Max allowed |Δ| of this path vs NumPy physical band (default 1e-4)",
    )
    args = parser.parse_args()
    out_path = Path(args.out)

    # Import the NumPy reference pipeline. The TF-Java JVM path matches
    # this line-for-line modulo accumulation order; the actual JVM
    # regeneration happens in CI via the tfjava-cube-cavity workflow
    # (sphere-mie-tfjava job) which builds + runs the Maven module.
    from reference.numpy.sphere_mie import (
        classify_modes_against_catalogue,
        load_mie_roots_catalogue,
        q_factor_from_lambda,
        run_sphere_mie,
    )

    print(f"Running NumPy tensor-ε UPML Mie pipeline "
          f"(σ₀={args.sigma0}, n_index={args.n_index}, k0_ref={args.k0_ref})...")
    print("(TF-Java JVM path is numerically equivalent modulo scatterNd accumulation order;")
    print(" actual JVM regeneration runs in CI via the tfjava-cube-cavity workflow.)")

    result = run_sphere_mie(
        args.mesh,
        sigma_0=args.sigma0,
        n_index=args.n_index,
        k0_ref=args.k0_ref,
        n_take=args.n_take,
    )

    n_nodes = result["n_nodes"]
    n_tets = result["n_tets"]
    eigvals_all = result["eigenvalues_all"]
    physical = result["physical_eigenvalues"]
    physical_ks = result["physical_ks"]
    q_factor = float(result["q_factor_lowest_physical"])

    print(f"  n_nodes = {n_nodes}, n_tets = {n_tets}")
    print(f"  n_edges = {result['n_edges']}, "
          f"n_interior_edges = {result['n_interior_edges']}")
    print(f"  spurious_dim = {result['spurious_dim']}, "
          f"n_spurious = {result['n_spurious']}")
    print(f"  Q_lowest_physical = {q_factor:.4f}")

    # J.1 analytic anchor + classification.
    roots = load_mie_roots_catalogue()
    tm11 = next(
        r for r in roots if r["pol"] == "TM" and r["l"] == 1 and r["n"] == 1
    )
    analytic_tm11_k = tm11["k"]
    table = classify_modes_against_catalogue(physical_ks, roots)
    lowest_re_k = float(physical_ks[0].real)
    rel_err_tm11 = abs(lowest_re_k - analytic_tm11_k) / analytic_tm11_k

    print(f"  lowest {args.n_take} physical λ (no sign canonicalization):")
    for lam, row in zip(physical, table):
        print(f"    {lam.real:+.6e} {lam.imag:+.6e}j  ->  "
              f"{row['pol']}_{row['l']},{row['n']} "
              f"(rel err = {row['rel_err'] * 100:.2f}%)")
    print(f"  lowest mode vs analytic TM_1,1 (k = {analytic_tm11_k:.6f}): "
          f"rel err = {rel_err_tm11 * 100:.2f}%")

    assert table[0]["pol"] == "TM" and table[0]["l"] == 1 and table[0]["n"] == 1, (
        f"lowest physical mode classified as "
        f"{table[0]['pol']}_{table[0]['l']},{table[0]['n']} — expected TM_1,1"
    )
    assert rel_err_tm11 < TM11_REL_TOL, (
        f"lowest mode rel err {rel_err_tm11 * 100:.2f}% exceeds the "
        f"documented {TM11_REL_TOL * 100:.0f}% acceptance band"
    )

    # Q tripwire + triplet median.
    triplet_qs = sorted(
        q_factor_from_lambda(lam) for lam in physical[:STRICT_MODE_WINDOW_LEN]
    )
    q_median_triplet = float(triplet_qs[1])
    print(f"  Q lowest = {q_factor:.4f}, TM_1,1 triplet median Q = "
          f"{q_median_triplet:.4f} (band > {Q_LOWER_BAND_TM11})")
    assert q_factor > Q_LOWER_BAND_TM11
    assert q_median_triplet > Q_LOWER_BAND_TM11

    # Cluster-closure sanity (#160).
    triplet_spread = float(
        physical[STRICT_MODE_WINDOW_LEN - 1].real - physical[0].real
    )
    gap_to_next = float(
        physical[STRICT_MODE_WINDOW_LEN].real
        - physical[STRICT_MODE_WINDOW_LEN - 1].real
    )
    print(f"  TM_1,1 triplet spread = {triplet_spread:.4f}, "
          f"gap to next band = {gap_to_next:.4f}")
    assert gap_to_next > 2.0 * triplet_spread, (
        "strict mode window does not end at a spectral gap — "
        "cluster-closure convention (#160) violated"
    )

    # σ₀ = 0 PEC anchor — the tensor collapses to real isotropic scalar ε.
    result_pec = run_sphere_mie(
        args.mesh,
        sigma_0=0.0,
        n_index=args.n_index,
        k0_ref=args.k0_ref,
        n_take=args.n_take,
    )
    pec_lowest_re = float(result_pec["physical_eigenvalues"][0].real)
    pec_max_imag_rel = float(result_pec["max_imag_eigval_rel"])
    print(f"  σ₀=0 PEC anchor: lowest physical Re(λ) = {pec_lowest_re:.6e}, "
          f"max|Im(λ)|/max(|Re(λ)|,1) = {pec_max_imag_rel:.3e}")
    assert pec_max_imag_rel < 1e-10

    # Cross-check vs the canonical NumPy J.2 small baseline.
    numpy_baseline_path = _numpy_baseline_path()
    verified_note: str
    if not numpy_baseline_path.exists():
        verified_note = (
            "NumPy sphere_mie_small baseline not found at generation time; "
            "cross-check skipped."
        )
        print(f"\nWARNING: {verified_note}")
    else:
        with open(numpy_baseline_path) as f:
            np_baseline = json.load(f)
        np_phys_field = np_baseline["outputs"].get("physical_eigenvalues_complex")
        if np_phys_field is None or np_phys_field.get("dtype") != "c128":
            verified_note = (
                "NumPy baseline present but lacks `physical_eigenvalues_complex` "
                "(c128); cross-check skipped."
            )
            print(f"\nWARNING: {verified_note}")
        else:
            np_flat = np.asarray(np_phys_field["data"], dtype=np.float64)
            np_complex = np_flat.view(np.complex128)
            n_compare = min(len(np_complex), len(physical))
            deltas = np.abs(np_complex[:n_compare] - physical[:n_compare])
            max_abs = float(np.max(deltas))
            d0 = float(deltas[0])
            print("\nCross-check vs NumPy J.2 canonical "
                  "`physical_eigenvalues_complex`:")
            print(f"  physical[0] |Δ|      = {d0:.3e}")
            print(f"  per-position max |Δ| = {max_abs:.3e} (over {n_compare} entries)")
            assert max_abs < args.tol, (
                f"physical band max |Δ| {max_abs:.3e} exceeds target "
                f"tolerance {args.tol:.0e} — the TF-Java fixture must pin "
                f"the same pencil as the J.2 baseline"
            )
            verified_note = (
                f"NumPy J.2 canonical (PR #179) `physical_eigenvalues_complex`: "
                f"physical[0] |Δ| = {d0:.3e}; per-position max |Δ| = "
                f"{max_abs:.3e} over {n_compare} entries (dense LAPACK ZGGEV "
                f"both sides — strict per-position diff). TF-Java JVM "
                f"scatterNd accumulation order is bit-equivalent to NumPy "
                f"COO->CSR within scatter-order ULP; the eigensolve matches "
                f"dense LAPACK ZGGEV exactly when called via the sidecar "
                f"driver (--problem sphere-mie --backend tfjava)."
            )

    fixture = {
        "schema_version": "1",
        "fixture_id": "sphere_mie_small/n48_aniso_upml_mie_tfjava",
        "description": (
            "TF-Java reference for the small-mesh anisotropic-UPML "
            "tensor-ε dielectric-sphere Mie eigenmode pipeline (Epic #88 "
            "/ Phase J.5 / Issue #174). TF-Java JVM driver "
            "(reference/tf_java/sphere_mie) does the per-element Nédélec "
            "curl-curl + diagonal-tensor complex-ε mass assembly via "
            "static-graph Ops + Session: the per-tet (ε_x, ε_y, ε_z) "
            "tensor enters as two parallel [nTets, 3] f64 placeholders "
            "(TF-Java 1.0.0 has no native c128 typed value) and the "
            "per-axis cofactor gram gg^(α)_pq = g_p[α] g_q[α] is "
            "contracted against it inside the graph, emitting Re(M) and "
            "Im(M) as parallel f64 tensors. The Python driver "
            "(reference/driver/eigensolve_from_sidecar.py --problem "
            "sphere-mie --backend tfjava) fuses the (Re, Im) pair into a "
            "SciPy complex128 pencil and runs dense LAPACK ZGGEV "
            "(matching reference/numpy/sphere_mie.py). NO sign "
            "canonicalization: physical Im(λ) < 0 on this small mesh's "
            "tensor pencil — a property of the pencil, not a solver "
            f"choice (J.2 fixture description). σ₀ = {args.sigma0}, "
            f"k₀_ref = {args.k0_ref}. {verified_note}"
        ),
        "units": (
            "λ = k² (inverse-length squared) under exp(+jωt); "
            "dimensionless mesh coordinates"
        ),
        "inputs": {
            "mesh_path": {
                "shape": [0],
                "dtype": "f64",
                "description": (
                    "Mesh fixture (relative to repo root): "
                    "reference/fixtures/sphere_pml_small/sphere.msh "
                    f"({n_nodes} nodes, {n_tets} tets) — shared with the "
                    "#158 sphere_pml_small fixture, not duplicated."
                ),
                "data": [],
            },
            "sigma_0": {
                "shape": [1],
                "dtype": "f64",
                "description": "UPML absorption strength at r=R_BUFFER.",
                "data": [float(result["sigma_0"])],
            },
            "k0_ref": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Reference wavenumber ω heuristic in the UPML stretch "
                    "s = 1 - jσ(r)/ω (K0_REF in mie_sphere.rs)."
                ),
                "data": [float(result["k0_ref"])],
            },
            "r_sphere": {
                "shape": [1],
                "dtype": "f64",
                "description": "Inner dielectric sphere radius.",
                "data": [1.0],
            },
            "r_pml_inner": {
                "shape": [1],
                "dtype": "f64",
                "description": "PML inner radius — start of the absorbing layer.",
                "data": [1.5],
            },
            "r_buffer": {
                "shape": [1],
                "dtype": "f64",
                "description": "Outer PEC wall radius.",
                "data": [2.0],
            },
            "n_index": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Refractive index inside the dielectric sphere; "
                    "ε_r = n² = 2.25 inside."
                ),
                "data": [float(result["n_index"])],
            },
            "epsilon_tensor_diag": {
                "shape": [int(n_tets), 3],
                "dtype": "c128",
                "description": (
                    "Per-tet diagonal anisotropic complex permittivity "
                    "tensor (ε_x, ε_y, ε_z), global Cartesian basis — "
                    "mirror of geode_core::build_anisotropic_pml_tensor_diag "
                    "(JVM twin: SphereMesh.buildAnisotropicPmlTensorDiag). "
                    "On-disk: row-major (tet, axis) flattened, real-imag "
                    "interleaved per reference/SCHEMA.md."
                ),
                "data": _interleave_c128(result["epsilon_tensor_diag"]),
            },
        },
        "outputs": {
            "n_nodes": {
                "shape": [1],
                "dtype": "f64",
                "description": "Number of mesh nodes.",
                "tolerance_abs": 0.5,
                "data": [float(n_nodes)],
            },
            "n_tets": {
                "shape": [1],
                "dtype": "f64",
                "description": "Number of mesh tets.",
                "tolerance_abs": 0.5,
                "data": [float(n_tets)],
            },
            "n_edges": {
                "shape": [1],
                "dtype": "f64",
                "description": "Number of globally-deduplicated edges.",
                "tolerance_abs": 0.5,
                "data": [float(result["n_edges"])],
            },
            "n_interior_edges": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Number of edges that survive PEC reduction (at least "
                    "one endpoint strictly inside the outer wall)."
                ),
                "tolerance_abs": 0.5,
                "data": [float(result["n_interior_edges"])],
            },
            "spurious_dim": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Predicted gradient-kernel dimension = number of mesh "
                    "nodes strictly inside the outer PEC wall."
                ),
                "tolerance_abs": 0.5,
                "data": [float(result["spurious_dim"])],
            },
            "n_spurious_observed": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Algebraic spurious-mode dimension = rank(d⁰_interior). "
                    "Invariant under the tensor-ε scaling on the mass."
                ),
                "tolerance_abs": 0.5,
                "data": [float(result["n_spurious"])],
            },
            "eigenvalues_lowest_complex": {
                "shape": [int(len(eigvals_all))],
                "dtype": "c128",
                "description": (
                    f"Lowest {len(eigvals_all)} = spurious_dim + 8 complex "
                    "eigenvalues of the tensor-ε pencil K x = λ M x, "
                    "sorted by |Re(λ)| ascending (Burn "
                    "FaerComplexEigensolver order). On-disk: real-imag "
                    "interleaved per reference/SCHEMA.md."
                ),
                "tolerance_abs": EIG_C128_TOL_ABS,
                "data": _interleave_c128(eigvals_all),
            },
            "physical_eigenvalues_complex": {
                "shape": [int(len(physical))],
                "dtype": "c128",
                "description": (
                    f"Lowest {len(physical)} physical complex eigenvalues "
                    "past the d⁰-rank spurious split, |Re(λ)| ascending. "
                    "Physical Im(λ) < 0 on this tensor pencil (see fixture "
                    "description). Strict cross-IR window = first "
                    "`strict_mode_window_len` entries (the closed TM_1,1 "
                    "triplet, #160 cluster-closure convention)."
                ),
                "tolerance_abs": PHYSICAL_C128_TOL_ABS,
                "data": _interleave_c128(physical),
            },
            "strict_mode_window_len": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Length of the strict cross-IR mode window: the "
                    "mesh-split TM_1,1 triplet (multiplicity 2l+1 = 3), "
                    "closed at a spectral gap per #160."
                ),
                "tolerance_abs": 0.5,
                "data": [float(STRICT_MODE_WINDOW_LEN)],
            },
            "analytic_tm11_k": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Analytic TM_1,1 root from the Phase J.1 catalogue "
                    "(reference/fixtures/mie_roots/baseline.json) — the "
                    "8% coarse-mesh acceptance anchor."
                ),
                "tolerance_abs": ANALYTIC_K_TOL_ABS,
                "data": [analytic_tm11_k],
            },
            "lowest_physical_re_k": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Re(k) = Re(√λ) (principal branch) of the lowest "
                    "physical mode."
                ),
                "tolerance_abs": RE_K_TOL_ABS,
                "data": [lowest_re_k],
            },
            "tm11_rel_err_lowest": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Relative error of the lowest physical Re(k) vs the "
                    "analytic TM_1,1 root (must stay below the 8% band)."
                ),
                "tolerance_abs": RE_K_TOL_ABS,
                "data": [rel_err_tm11],
            },
            "q_factor_lowest_physical": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Q = Re(k)/(2|Im(k)|) of the lowest physical mode "
                    "(sign-agnostic). Loose tolerance — dQ/dIm(λ) ≈ "
                    "Q/|Im(λ)| amplification; the load-bearing assertion "
                    "is the Q > 1.5 tripwire."
                ),
                "tolerance_abs": Q_FACTOR_TOL_ABS,
                "data": [q_factor],
            },
            "q_median_tm11_triplet": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Median Q over the TM_1,1 triplet (strict window) — "
                    "mirrors the mie_sphere_tm11_triplet_q_above_band "
                    "Burn-side tripwire (Q_LOWER_BAND_TM11 = 1.5)."
                ),
                "tolerance_abs": Q_FACTOR_TOL_ABS,
                "data": [q_median_triplet],
            },
            "sigma_zero_lowest_physical_re": {
                "shape": [1],
                "dtype": "f64",
                "description": (
                    "Lowest physical Re(λ) at σ₀ = 0 (PEC limit; the "
                    "tensor collapses to real isotropic scalar ε)."
                ),
                "tolerance_abs": SIGMA_ZERO_RE_TOL_ABS,
                "data": [pec_lowest_re],
            },
        },
        "provenance": {
            "source": (
                f"reference/tf_java/sphere_mie @ commit {_git_commit()} "
                f"(Epic #88 / Phase J.5 / Issue #174). Numerically "
                f"equivalent to reference/numpy/sphere_mie.py through the "
                f"tensor-ε assembly + ZGGEV seam; TF-Java scatterNd "
                f"accumulation order produces ~1e-10 to ~1e-5 drift on "
                f"individual eigenvalues (documented Phase G.5 PR #137 "
                f"friction artifact). Live JVM regeneration + hard gate: "
                f".github/workflows/tfjava-cube-cavity.yml "
                f"(sphere-mie-tfjava job)."
            ),
            "verified_against": verified_note,
            "issue": "#174 (parent epic #88, Phase J.5; J.2 source #171, anchor #170)",
        },
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(fixture, f, indent=2)
        f.write("\n")
    print(f"\nWrote {out_path} ({os.path.getsize(out_path)} bytes)")
    print(f"  generator_commit = {_git_commit()}")


if __name__ == "__main__":
    main()
