//! **Freeform inverse-design on the curved conformal radiator** integration
//! test (issue #650, Epic #647 headline artifact) — the first *many-DOF* shape
//! optimization loop on genuinely curved conformal metal, over a *band* of
//! frequencies (v1 spec = impedance match + bandwidth).
//!
//! The load-bearing composed-gradient FD gate on the curved geometry lives in
//! the library unit test `mesh::patch::tests::
//! curved_conformal_composed_gradient_matches_central_finite_difference` (the
//! composed adjoint vs a central finite difference of the public
//! `driven_solve_with_ports(MatchedUpml)` pipeline, on the curved mesh). This
//! CI-fast integration test **pins the committed benchmark artifact**
//! `benchmarks/patch_antenna_conformal/conformal_results.toml` (generated by
//! `cargo run -p geode-core --release --example patch_conformal_diffopt`)
//! against silent regeneration drift: the many-DOF freeform band gradient
//! passed its own FD gate on the curved mesh, one factorization per band
//! frequency, `|S₁₁| ≤ 1` passivity held across the whole band throughout, the
//! per-tet non-inversion guard was respected, the descent is monotone, the
//! design is non-obvious (many independent DOFs), the descent stopped on a
//! GENUINE terminal condition (the −10 dB target, a vanishing gradient, the
//! guard binding, or a true plateau — never the bare step cap), and the recorded
//! outcome (a freeform band match to −10 dB, or a genuinely-diagnosed negative)
//! is internally consistent with its terminal flags.

use std::path::PathBuf;

/// Read a TOML number as `f64` whether it serialized as a float or an integer
/// (whole-valued fields like `target_db = -10` land as TOML integers).
fn num(v: &toml::Value) -> f64 {
    v.as_float()
        .or_else(|| v.as_integer().map(|i| i as f64))
        .unwrap_or_else(|| panic!("expected a number, got {v:?}"))
}

fn committed() -> toml::Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../benchmarks/patch_antenna_conformal/conformal_results.toml");
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    toml::from_str(&text).expect("parse conformal_results.toml")
}

/// The committed conformal artifact satisfies the issue #650 acceptance criteria.
#[test]
fn committed_conformal_results_meet_acceptance_criteria() {
    let doc = committed();

    // --- Generated on the curved conformal geometry (Phase 2, #649). ---
    let fixture = doc["meta"]["fixture"].as_str().unwrap();
    assert!(
        fixture.contains("bent_conformal"),
        "conformal artifact must be the curved (bent_conformal) fixture, got {fixture:?}"
    );
    assert!(
        num(&doc["meta"]["bend_radius_mm"]) > 0.0,
        "curved fixture must record a positive bend radius"
    );

    // --- MANY active freeform DOFs (Phase 1, #648): the run is genuinely
    //     high-DOF, not a single parametric knob. ---
    let n_dofs = doc["meta"]["n_freeform_dofs"].as_integer().unwrap();
    assert!(
        n_dofs >= 4,
        "expected MANY freeform DOFs (high-DOF parametrization), got {n_dofs}"
    );
    assert_eq!(
        doc["shape"]["n_dofs"].as_integer().unwrap(),
        n_dofs,
        "shape design-vector DOF count must match the meta count"
    );
    let dv = doc["shape"]["design_vector"].as_array().unwrap();
    assert_eq!(
        dv.len() as i64,
        n_dofs,
        "design vector length must equal n_dofs"
    );
    // Non-obvious: at least several DOFs move independently (not all equal —
    // not reproducible by a single knob).
    let vals: Vec<f64> = dv.iter().map(|v| v.as_float().unwrap()).collect();
    let n_distinct_signs = {
        let pos = vals.iter().filter(|&&v| v > 1e-6).count();
        let neg = vals.iter().filter(|&&v| v < -1e-6).count();
        pos.min(neg)
    };
    assert!(
        n_distinct_signs >= 1,
        "optimized shape is not freeform (design vector has no sign variation — a single knob)"
    );
    assert!(
        doc["model"]["non_obvious"].as_bool().unwrap_or(false),
        "artifact must record the non-obvious (many-DOF) geometry flag"
    );

    // --- Band (bandwidth) spec: more than one design frequency. ---
    let band = doc["meta"]["band_omega"].as_array().unwrap();
    assert!(
        band.len() >= 2,
        "v1 bandwidth spec needs a band of frequencies, got {}",
        band.len()
    );
    let target_db = num(&doc["meta"]["target_db"]);
    assert!(
        (target_db + 10.0).abs() < 1e-9,
        "v1 match target must be -10 dB, got {target_db}"
    );

    // --- FD gate: the full multi-DOF / multi-frequency band gradient
    //     FD-validated on the curved mesh, one factorization per band freq. ---
    let fd = &doc["fd_validation"];
    let rel = fd["rel_err"].as_float().unwrap();
    let tol = fd["tolerance"].as_float().unwrap();
    assert!(
        (tol - 5e-3).abs() < 1e-12,
        "FD tolerance must be the 5e-3 acceptance bar, got {tol}"
    );
    assert!(
        rel <= tol,
        "committed FD rel-err {rel} exceeds tolerance {tol}"
    );
    assert!(
        rel < 1e-4,
        "committed FD rel-err regressed above 1e-4: {rel}"
    );
    assert_eq!(
        fd["n_factorizations_per_freq"].as_integer().unwrap(),
        1,
        "composed adjoint must reuse the single forward LU per band frequency"
    );

    // --- Passivity + monotone descent across the trajectory. ---
    let steps = doc["trajectory"]["step"].as_array().unwrap();
    assert!(steps.len() >= 2, "trajectory too short");
    let mut prev = f64::INFINITY;
    for s in steps {
        let g = s["band_objective"].as_float().unwrap();
        assert!(
            g < prev + 1e-15,
            "band objective not monotone: {g} !< {prev}"
        );
        prev = g;
        // Worst-of-band |S11| implied dB must be a passive reflection (<= 0 dB).
        let wdb = s["worst_s11_db"].as_float().unwrap();
        assert!(
            wdb <= 1e-6,
            "passive one-port violated in trajectory: worst |S11| = {wdb} dB > 0"
        );
        // Non-inversion guard respected at every recorded step.
        let vr = s["min_vol_ratio"].as_float().unwrap();
        assert!(
            vr > 0.0,
            "a tet inverted in the trajectory (vol ratio {vr})"
        );
    }

    // --- Per-frequency final |S11|(f) recorded and passive. ---
    let band_pts = doc["s11_band"]["point"].as_array().unwrap();
    assert_eq!(
        band_pts.len(),
        band.len(),
        "per-frequency S11 record must cover the whole band"
    );
    for p in band_pts {
        let mag = p["s11_mag"].as_float().unwrap();
        assert!(
            mag <= 1.0 + 1e-9,
            "per-frequency |S11| = {mag} exceeds the passive bound"
        );
        let db = p["s11_db"].as_float().unwrap();
        assert!(
            (db - 20.0 * mag.log10()).abs() < 1e-4,
            "s11_db {db} inconsistent with |S11| {mag}"
        );
    }

    // --- Objective reduction + non-inversion budget over the whole run. ---
    let opt = &doc["optimization"];
    let g_init = opt["band_objective_initial"].as_float().unwrap();
    let g_final = opt["band_objective_final"].as_float().unwrap();
    assert!(
        g_final < g_init,
        "band objective did not decrease: {g_final} !< {g_init}"
    );
    let worst = opt["worst_vol_ratio"].as_float().unwrap();
    let budget = doc["model"]["min_vol_ratio_budget"].as_float().unwrap();
    assert!(
        worst >= budget,
        "worst per-tet vol ratio {worst} fell below the non-inversion budget {budget}"
    );
    assert!(worst > 0.0, "a tet inverted (vol ratio {worst})");

    // --- Recorded outcome internally consistent (positive dip OR honest-neg). ---
    let reached = opt["reached_target"].as_bool().unwrap();
    let wdb_final = opt["worst_s11_db_final"].as_float().unwrap();
    let outcome = opt["outcome"].as_str().unwrap();
    if reached {
        assert!(
            wdb_final <= -10.0,
            "reached_target=true but worst-of-band |S11| = {wdb_final} dB is not <= -10 dB"
        );
        assert_eq!(
            outcome, "freeform_band_match_-10dB",
            "outcome string inconsistent with reached_target=true"
        );
    } else {
        assert!(
            wdb_final > -10.0,
            "reached_target=false but worst-of-band |S11| = {wdb_final} dB is <= -10 dB"
        );
        assert_eq!(
            outcome, "honest_negative",
            "outcome string inconsistent with reached_target=false"
        );
    }
    assert!(
        opt["diagnosis"].as_str().is_some_and(|d| !d.is_empty()),
        "a physics/distortion diagnosis must be recorded for either outcome"
    );

    // --- The stop was a GENUINE terminal condition, never the bare step cap.
    //     The Phase-3 headline requires the descent to reach an ACTUAL limit —
    //     the −10 dB target, a vanishing gradient, the non-inversion guard
    //     binding, or a true objective plateau — with the recorded flags
    //     (`converged`, `distortion_limited`, `reached_target`) matching that
    //     terminal. This is the assertion that forbids a step-budget-limited
    //     early stop being mis-recorded as a physics/mesh cap. ---
    let terminal = opt["terminal_condition"].as_str().unwrap();
    assert_ne!(
        terminal, "max_steps",
        "run terminated on the bare step cap (max_steps) — not a genuine limit; a diagnosis \
         claiming a physics/mesh cap would be unsupported"
    );
    let n_steps = opt["n_steps"].as_integer().unwrap();
    let max_steps = opt["max_steps"].as_integer().unwrap();
    assert!(
        n_steps < max_steps,
        "n_steps {n_steps} hit max_steps {max_steps}: step-budget-limited, not a genuine terminal"
    );
    let converged = opt["converged"].as_bool().unwrap();
    let distortion_limited = opt["distortion_limited"].as_bool().unwrap();
    let worst_vr = opt["worst_vol_ratio"].as_float().unwrap();
    let budget = doc["model"]["min_vol_ratio_budget"].as_float().unwrap();
    match terminal {
        // POSITIVE: the whole band cleared −10 dB.
        "target_reached" => {
            assert!(reached, "terminal=target_reached but reached_target=false");
            assert!(
                !converged && !distortion_limited,
                "target_reached must not also set a gradient/plateau or distortion limit flag"
            );
        }
        // GENUINE NEGATIVE: gradient vanished at a stationary point.
        "converged_grad_norm" => {
            assert!(
                converged && !distortion_limited,
                "converged_grad_norm must set converged=true, distortion_limited=false"
            );
            let gtol = opt["grad_tol"].as_float().unwrap();
            let gfin = opt["grad_norm_final"].as_float().unwrap();
            assert!(
                gfin < gtol,
                "converged_grad_norm but grad_norm_final {gfin} !< grad_tol {gtol}"
            );
        }
        // GENUINE NEGATIVE: a true objective plateau / local minimum.
        "plateau" | "line_search_stall" => {
            assert!(
                converged && !distortion_limited,
                "{terminal} must set converged=true, distortion_limited=false"
            );
        }
        // GENUINE NEGATIVE: the non-inversion guard actually bound.
        "distortion_limited" => {
            assert!(
                distortion_limited && !converged,
                "distortion_limited must set distortion_limited=true, converged=false"
            );
            assert!(
                worst_vr <= budget * 1.05 + 1e-12,
                "distortion_limited claimed, but worst vol ratio {worst_vr} is not near the \
                 non-inversion budget {budget} — the guard did not actually bind"
            );
        }
        other => panic!("unknown terminal_condition {other:?}"),
    }

    // --- Fresh, independent forward at X_final agrees with the optimizer. ---
    let cc = &doc["cross_check"];
    let fresh_rel = cc["fresh_vs_optimizer_rel"].as_float().unwrap();
    assert!(
        fresh_rel < 1e-6,
        "fresh forward vs optimizer band objective disagree: rel {fresh_rel}"
    );
}
