"""Benchmark-TOML loader for the geode_viz package.

Loads ``benchmarks/<name>/<file>.toml`` into a plain Python dict and
surfaces fixture provenance (``fixture_sha256``, ``generated_at_commit``)
so downstream plot modules can stamp a uniform footer (see
:func:`geode_viz.style.footer`).

The benchmark TOMLs are auto-generated by ``cargo run --example ...``
and follow a consistent ``[meta]`` block convention:

- ``description`` (str, free text)
- ``fixture`` (str, repo-relative MSH path) — *optional* on benchmarks
  that don't bind to a mesh (e.g. ``perf``).
- ``fixture_sha256`` (str, 64 hex chars) — *optional* but stable when
  present.
- ``generated_at_commit`` (str, 40 hex chars) — always present.

Don't invent new keys here; downstream plot modules should drill into
the benchmark-specific tables on the returned dict
(``results["oracles"]["mohan"]["current_sheet_l_nh"]`` etc.) directly.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

from geode_viz.paths import repo_root

# Python 3.11+ has stdlib tomllib; tomli is the back-compat dep declared
# in pyproject.toml. Both expose the same load/loads surface. Some
# interpreters ship a trimmed stdlib without tomllib (notably ParaView's
# bundled Python, under which the VTK render scripts in geode_viz.scripts
# import this package but never call load_results) — defer the failure to
# the actual TOML read instead of breaking module import there.
try:
    import tomllib as _toml  # Python 3.11+ stdlib
except ModuleNotFoundError:  # <3.11, or a trimmed stdlib (e.g. pvbatch)
    try:
        import tomli as _toml
    except ModuleNotFoundError:  # pragma: no cover — no TOML parser at all
        _toml = None


class BenchmarkNotFound(FileNotFoundError):
    """Raised when no candidate TOML matches the benchmark request."""


# Per-benchmark default file priority. The first existing file wins
# unless an explicit ``filename=`` argument overrides. ``results.toml``
# is the canonical default for every benchmark that has one; ``pattern``
# / ``driven`` / ``open`` are the multi-mode variants that downstream
# plots care about.
_DEFAULT_PRIORITY: tuple[str, ...] = (
    "results.toml",
    "results_matched.toml",
    "driven_results.toml",
    "pattern.toml",
    "pattern_matched.toml",
    "open_results.toml",
    "baseline.toml",
)


def _benchmarks_root() -> Path:
    return repo_root() / "benchmarks"


def _candidate_paths(benchmark: str, filename: str | None) -> Iterable[Path]:
    bench_dir = _benchmarks_root() / benchmark
    if filename is not None:
        yield bench_dir / filename
        return
    for name in _DEFAULT_PRIORITY:
        yield bench_dir / name


def load_results(benchmark: str, filename: str | None = None) -> dict[str, Any]:
    """Load a benchmark TOML and return its parsed structure.

    Parameters
    ----------
    benchmark
        Benchmark name — the directory under ``benchmarks/`` (e.g.
        ``"spiral_inductor"``, ``"mie_sphere"``, ``"patch_antenna"``).
    filename
        Optional explicit filename (e.g. ``"pattern.toml"``,
        ``"driven_results_fine.toml"``). When ``None``, the loader
        walks the default priority list and returns the first match.

    Returns
    -------
    dict
        The parsed TOML as a plain Python dict. The ``[meta]`` block
        is exposed at ``result["meta"]`` and always contains
        ``generated_at_commit``; ``fixture`` / ``fixture_sha256``
        appear on benchmarks that bind to a mesh fixture.

    Raises
    ------
    BenchmarkNotFound
        If no candidate TOML exists for the request.
    """
    if _toml is None:  # pragma: no cover — trimmed interpreter w/o a parser
        raise ModuleNotFoundError(
            "no TOML parser available: this interpreter lacks stdlib "
            "'tomllib' (Python <3.11 or a trimmed build such as ParaView's "
            "bundled Python) and 'tomli' is not installed. Install 'tomli', "
            "or run benchmark-TOML plotting under a standard Python 3.11+."
        )
    for path in _candidate_paths(benchmark, filename):
        if path.is_file():
            with path.open("rb") as f:
                data = _toml.load(f)
            # Stash the source path under a non-colliding underscore key
            # so downstream plot modules can reference it in titles /
            # provenance footers without re-discovering it.
            data.setdefault("_source", {})["path"] = str(
                path.relative_to(repo_root())
            )
            return data
    bench_dir = _benchmarks_root() / benchmark
    if not bench_dir.is_dir():
        raise BenchmarkNotFound(
            f"benchmark directory does not exist: {bench_dir}"
        )
    tried = [str(p.relative_to(repo_root())) for p in _candidate_paths(benchmark, filename)]
    raise BenchmarkNotFound(
        f"no matching TOML for benchmark {benchmark!r} "
        f"(tried: {tried})"
    )


def provenance(results: dict[str, Any]) -> dict[str, str]:
    """Extract the ``[meta]`` provenance fields used by plot footers.

    Returns a dict with the keys downstream plots stamp on every
    figure: ``commit`` (always present), ``fixture`` (may be empty
    string), ``fixture_sha256`` (may be empty string), ``source``
    (the repo-relative TOML path).

    The empty-string fallback is deliberate — figure footers want a
    fixed-shape string, not ``None``-renders-as-"None".
    """
    meta = results.get("meta", {})
    return {
        "commit": str(meta.get("generated_at_commit", "")),
        "fixture": str(meta.get("fixture", "")),
        "fixture_sha256": str(meta.get("fixture_sha256", "")),
        "source": str(results.get("_source", {}).get("path", "")),
    }
